"""
This type stub file was generated by pyright.
"""

import numpy as np
from pathlib import Path
from typing import Any, Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import FileSerializable
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Changeable, Clearable, Playable, Recordable, Streamable, StreamableOutput, Uploadable
from gradio.interpretation import TokenInterpretable

"""gr.Audio() component."""
@document()
class Audio(Changeable, Clearable, Playable, Recordable, Streamable, StreamableOutput, Uploadable, IOComponent, FileSerializable, TokenInterpretable):
    """
    Creates an audio component that can be used to upload/record audio (as an input) or display audio (as an output).
    Preprocessing: passes the uploaded audio as a {Tuple(int, numpy.array)} corresponding to (sample rate in Hz, audio data as a 16-bit int array whose values range from -32768 to 32767), or as a {str} filepath, depending on `type`.
    Postprocessing: expects a {Tuple(int, numpy.array)} corresponding to (sample rate in Hz, audio data as a float or int numpy array) or as a {str} or {pathlib.Path} filepath or URL to an audio file, or bytes for binary content (recommended for streaming)
    Examples-format: a {str} filepath to a local file that contains audio.
    Demos: main_note, generate_tone, reverse_audio
    Guides: real-time-speech-recognition
    """
    def __init__(self, value: str | Path | tuple[int, np.ndarray] | Callable | None = ..., *, source: Literal["upload", "microphone"] | None = ..., type: Literal["numpy", "filepath"] = ..., label: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., format: Literal["wav", "mp3"] = ..., autoplay: bool = ..., show_download_button=..., show_share_button: bool | None = ..., show_edit_button: bool | None = ..., **kwargs) -> None:
        """
        Parameters:
            value: A path, URL, or [sample_rate, numpy array] tuple (sample rate in Hz, audio data as a float or int numpy array) for the default value that Audio component is going to take. If callable, the function will be called whenever the app loads to set the initial value of the component.
            source: Source of audio. "upload" creates a box where user can drop an audio file, "microphone" creates a microphone input.
            type: The format the audio file is converted to before being passed into the prediction function. "numpy" converts the audio to a tuple consisting of: (int sample rate, numpy.array for the data), "filepath" passes a str path to a temporary file containing the audio.
            label: component name in interface.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            interactive: if True, will allow users to upload and edit a audio file; if False, can only be used to play audio. If not provided, this is inferred based on whether the component is used as an input or output.
            visible: If False, component will be hidden.
            streaming: If set to True when used in a `live` interface as an input, will automatically stream webcam feed. When used set as an output, takes audio chunks yield from the backend and combines them into one streaming audio output.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            format: The file format to save audio files. Either 'wav' or 'mp3'. wav files are lossless but will tend to be larger files. mp3 files tend to be smaller. Default is wav. Applies both when this component is used as an input (when `type` is "format") and when this component is used as an output.
            autoplay: Whether to automatically play the audio when the component is used as an output. Note: browsers will not autoplay audio files if the user has not interacted with the page yet.
            show_download_button: If True, will show a download button in the corner of the component for saving audio. If False, icon does not appear.
            show_share_button: If True, will show a share icon in the corner of the component that allows user to share outputs to Hugging Face Spaces Discussions. If False, icon does not appear. If set to None (default behavior), then the icon appears if this Gradio app is launched on Spaces, but not otherwise.
            show_edit_button: If True, will show an edit icon in the corner of the component that allows user to edit the audio. If False, icon does not appear. Default is True.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def example_inputs(self) -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: Any | Literal[_Keywords.NO_VALUE] | None = ..., source: Literal["upload", "microphone"] | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., interactive: bool | None = ..., visible: bool | None = ..., autoplay: bool | None = ..., show_download_button: bool | None = ..., show_share_button: bool | None = ..., show_edit_button: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def preprocess(self, x: dict[str, Any] | None) -> tuple[int, np.ndarray] | str | None:
        """
        Parameters:
            x: dictionary with keys "name", "data", "is_file", "crop_min", "crop_max".
        Returns:
            audio in requested format
        """
        ...
    
    def set_interpret_parameters(self, segments: int = ...): # -> Self:
        """
        Calculates interpretation score of audio subsections by splitting the audio into subsections, then using a "leave one out" method to calculate the score of each subsection by removing the subsection and measuring the delta of the output value.
        Parameters:
            segments: Number of interpretation segments to split audio into.
        """
        ...
    
    def tokenize(self, x): # -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[Any]]:
        ...
    
    def get_masked_inputs(self, tokens, binary_mask_matrix): # -> list[Any]:
        ...
    
    def postprocess(self, y: tuple[int, np.ndarray] | str | Path | bytes | None) -> str | dict | bytes | None:
        """
        Parameters:
            y: audio data in either of the following formats: a tuple of (sample_rate, data), or a string filepath or URL to an audio file, or None.
        Returns:
            base64 url data
        """
        ...
    
    def stream_output(self, y, output_id: str, first_chunk: bool): # -> tuple[None, dict[str, Any]] | tuple[bytes, dict[str, Any]] | tuple[bytes | Any, dict[str, Any]]:
        ...
    
    def check_streamable(self): # -> None:
        ...
    
    def as_example(self, input_data: str | None) -> str:
        ...
    


