"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Callable, Literal
from gradio_client.documentation import document
from gradio.components.base import _Keywords
from gradio.components.plot import Plot

"""gr.BarPlot() component."""
@document()
class BarPlot(Plot):
    """
    Create a bar plot.

    Preprocessing: this component does *not* accept input.
    Postprocessing: expects a pandas dataframe with the data to plot.

    Demos: bar_plot, chicago-bikeshare-dashboard
    """
    def __init__(self, value: pd.DataFrame | Callable | None = ..., x: str | None = ..., y: str | None = ..., *, color: str | None = ..., vertical: bool = ..., group: str | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., group_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., y_lim: list[int] | None = ..., caption: str | None = ..., interactive: bool | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., every: float | None = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ...) -> None:
        """
        Parameters:
            value: The pandas dataframe containing the data to display in a scatter plot.
            x: Column corresponding to the x axis.
            y: Column corresponding to the y axis.
            color: The column to determine the bar color. Must be categorical (discrete values).
            vertical: If True, the bars will be displayed vertically. If False, the x and y axis will be switched, displaying the bars horizontally. Default is True.
            group: The column with which to split the overall plot into smaller subplots.
            title: The title to display on top of the chart.
            tooltip: The column (or list of columns) to display on the tooltip when a user hovers over a bar.
            x_title: The title given to the x axis. By default, uses the value of the x parameter.
            y_title: The title given to the y axis. By default, uses the value of the y parameter.
            x_label_angle: The angle (in degrees) of the x axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            y_label_angle: The angle (in degrees) of the y axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            color_legend_title: The title given to the color legend. By default, uses the value of color parameter.
            group_title: The label displayed on top of the subplot columns (or rows if vertical=True). Use an empty string to omit.
            color_legend_position: The position of the color legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            height: The height of the plot in pixels.
            width: The width of the plot in pixels.
            y_lim: A tuple of list containing the limits for the y-axis, specified as [y_min, y_max].
            caption: The (optional) caption to display below the plot.
            interactive: Whether users should be able to interact with the plot by panning or zooming with their mouse or trackpad.
            label: The (optional) label to display on the top left corner of the plot.
            show_label: Whether the label should be displayed.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            visible: Whether the plot should be visible.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def get_block_name(self) -> str:
        ...
    
    @staticmethod
    def update(value: pd.DataFrame | dict | Literal[_Keywords.NO_VALUE] = ..., x: str | None = ..., y: str | None = ..., color: str | None = ..., vertical: bool = ..., group: str | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., group_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., y_lim: list[int] | None = ..., caption: str | None = ..., interactive: bool | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        """Update an existing BarPlot component.

        If updating any of the plot properties (color, size, etc) the value, x, and y parameters must be specified.

        Parameters:
            value: The pandas dataframe containing the data to display in a scatter plot.
            x: Column corresponding to the x axis.
            y: Column corresponding to the y axis.
            color: The column to determine the bar color. Must be categorical (discrete values).
            vertical: If True, the bars will be displayed vertically. If False, the x and y axis will be switched, displaying the bars horizontally. Default is True.
            group: The column with which to split the overall plot into smaller subplots.
            title: The title to display on top of the chart.
            tooltip: The column (or list of columns) to display on the tooltip when a user hovers over a bar.
            x_title: The title given to the x axis. By default, uses the value of the x parameter.
            y_title: The title given to the y axis. By default, uses the value of the y parameter.
            x_label_angle: The angle (in degrees) of the x axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            y_label_angle: The angle (in degrees) of the y axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            color_legend_title: The title given to the color legend. By default, uses the value of color parameter.
            group_title: The label displayed on top of the subplot columns (or rows if vertical=True). Use an empty string to omit.
            color_legend_position: The position of the color legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            height: The height of the plot in pixels.
            width: The width of the plot in pixels.
            y_lim: A tuple of list containing the limits for the y-axis, specified as [y_min, y_max].
            caption: The (optional) caption to display below the plot.
            interactive: Whether users should be able to interact with the plot by panning or zooming with their mouse or trackpad.
            label: The (optional) label to display on the top left corner of the plot.
            show_label: Whether the label should be displayed.
            visible: Whether the plot should be visible.
        """
        ...
    
    @staticmethod
    def create_plot(value: pd.DataFrame, x: str, y: str, color: str | None = ..., vertical: bool = ..., group: str | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., group_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., y_lim: list[int] | None = ..., interactive: bool | None = ...): # -> Chart:
        """Helper for creating the bar plot."""
        ...
    
    def postprocess(self, y: pd.DataFrame | dict | None) -> dict[str, str] | None:
        ...
    


