"""
This type stub file was generated by pyright.
"""

from gradio_client.serializing import SimpleSerializable
from gradio.components.base import IOComponent
from gradio.events import Changeable

"""gr.Carousel() component."""
class Carousel(IOComponent, Changeable, SimpleSerializable):
    """
    Deprecated Component
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    


