"""
This type stub file was generated by pyright.
"""

from typing import Literal
from gradio_client.documentation import document
from gradio.components import Button, Component

""" Predefined buttons with bound events that can be included in a gr.Blocks for convenience. """
@document("add")
class ClearButton(Button):
    """
    Button that clears the value of a component or a list of components when clicked. It is instantiated with the list of components to clear.
    Preprocessing: passes the button value as a {str} into the function
    Postprocessing: expects a {str} to be returned from a function, which is set as the label of the button
    """
    is_template = ...
    def __init__(self, components: None | list[Component] | Component = ..., *, value: str = ..., variant: Literal["primary", "secondary", "stop"] = ..., size: Literal["sm", "lg"] | None = ..., icon: str | None = ..., link: str | None = ..., visible: bool = ..., interactive: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., scale: int | None = ..., min_width: int | None = ..., **kwargs) -> None:
        ...
    
    def add(self, components: None | Component | list[Component]) -> ClearButton:
        """
        Adds a component or list of components to the list of components that will be cleared when the button is clicked.
        """
        ...
    


