"""
This type stub file was generated by pyright.
"""

from typing import Literal
from gradio_client.documentation import document
from gradio_client.serializing import StringSerializable
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Changeable, Inputable

"""gr.Code() component"""
@document()
class Code(Changeable, Inputable, IOComponent, StringSerializable):
    """
    Creates a Code editor for entering, editing or viewing code.
    Preprocessing: passes a {str} of code into the function.
    Postprocessing: expects the function to return a {str} of code or a single-elment {tuple}: (string filepath,)
    """
    languages = ...
    def __init__(self, value: str | tuple[str] | None = ..., language: Literal["python", "markdown", "json", "html", "css", "javascript", "typescript", "yaml", "dockerfile", "shell", "r",] | None = ..., *, lines: int = ..., label: str | None = ..., interactive: bool | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., **kwargs) -> None:
        """
        Parameters:
            value: Default value to show in the code editor. If callable, the function will be called whenever the app loads to set the initial value of the component.
            language: The language to display the code as. Supported languages listed in `gr.Code.languages`.
            label: component name in interface.
            interactive: Whether user should be able to enter code or only view it.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def postprocess(self, y): # -> str | None:
        ...
    
    @staticmethod
    def update(value: str | tuple[str] | None | Literal[_Keywords.NO_VALUE] = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ..., language: Literal["python", "markdown", "json", "html", "css", "javascript", "typescript", "yaml", "dockerfile", "shell", "r",] | None = ..., interactive: bool | None = ...): # -> dict[str, Any]:
        ...
    


