"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import SimpleSerializable
from gradio.components.base import FormComponent, IOComponent, _Keywords
from gradio.events import Changeable, Focusable, Inputable, Selectable

"""gr.Dropdown() component."""
@document()
class Dropdown(FormComponent, Changeable, Inputable, Selectable, Focusable, IOComponent, SimpleSerializable):
    """
    Creates a dropdown of choices from which entries can be selected.
    Preprocessing: passes the value of the selected dropdown entry as a {str} or its index as an {int} into the function, depending on `type`.
    Postprocessing: expects a {str} corresponding to the value of the dropdown entry to be selected.
    Examples-format: a {str} representing the drop down value to select.
    Demos: sentence_builder, titanic_survival
    """
    def __init__(self, choices: list[str] | None = ..., *, value: str | list[str] | Callable | None = ..., type: Literal["value", "index"] = ..., multiselect: bool | None = ..., allow_custom_value: bool = ..., max_choices: int | None = ..., label: str | None = ..., info: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., **kwargs) -> None:
        """
        Parameters:
            choices: list of options to select from.
            value: default value(s) selected in dropdown. If None, no value is selected by default. If callable, the function will be called whenever the app loads to set the initial value of the component.
            type: Type of value to be returned by component. "value" returns the string of the choice selected, "index" returns the index of the choice selected.
            multiselect: if True, multiple choices can be selected.
            allow_custom_value: If True, allows user to enter a custom value that is not in the list of choices. Only applies if `multiselect` is False.
            max_choices: maximum number of choices that can be selected. If None, no limit is enforced.
            label: component name in interface.
            info: additional component description.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            interactive: if True, choices in this dropdown will be selectable; if False, selection will be disabled. If not provided, this is inferred based on whether the component is used as an input or output.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def api_info(self) -> dict[str, dict | bool]:
        ...
    
    def example_inputs(self) -> dict[str, Any]:
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: Any | Literal[_Keywords.NO_VALUE] | None = ..., choices: str | list[str] | None = ..., label: str | None = ..., info: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., interactive: bool | None = ..., placeholder: str | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def preprocess(self, x: str | list[str]) -> str | int | list[str] | list[int] | None:
        """
        Parameters:
            x: selected choice(s)
        Returns:
            selected choice(s) as string or index within choice list or list of string or indices
        """
        ...
    
    def set_interpret_parameters(self): # -> Self:
        """
        Calculates interpretation score of each choice by comparing the output against each of the outputs when alternative choices are selected.
        """
        ...
    
    def get_interpretation_neighbors(self, x): # -> tuple[list[str], dict[Any, Any]]:
        ...
    
    def get_interpretation_scores(self, x, neighbors, scores: list[float | None], **kwargs) -> list:
        """
        Returns:
            Each value represents the interpretation score corresponding to each choice.
        """
        ...
    
    def style(self, *, container: bool | None = ..., **kwargs): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


