"""
This type stub file was generated by pyright.
"""

from typing import Literal
from gradio_client.documentation import document
from gradio.components import Button

""" Predefined buttons with bound events that can be included in a gr.Blocks for convenience. """
@document()
class DuplicateButton(Button):
    """
    Button that triggers a Spaces Duplication, when the demo is on Hugging Face Spaces. Does nothing locally.
    Preprocessing: passes the button value as a {str} into the function
    Postprocessing: expects a {str} to be returned from a function, which is set as the label of the button
    """
    is_template = ...
    def __init__(self, *, value: str = ..., variant: Literal["primary", "secondary", "stop"] = ..., size: Literal["sm", "lg"] | None = ..., icon: str | None = ..., link: str | None = ..., visible: bool = ..., interactive: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., scale: int | None = ..., min_width: int | None = ..., _activate: bool = ..., **kwargs) -> None:
        """
        Parameters:
            value: Default text for the button to display. If callable, the function will be called whenever the app loads to set the initial value of the component.
            variant: 'primary' for main call-to-action, 'secondary' for a more subdued style, 'stop' for a stop button.
            size: Size of the button. Can be "sm" or "lg".
            icon: URL or path to the icon file to display within the button. If None, no icon will be displayed.
            link: URL to open when the button is clicked. If None, no link will be used.
            visible: If False, component will be hidden.
            interactive: If False, the Button will be in a disabled state.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
        """
        ...
    
    def activate(self): # -> None:
        ...
    


