"""
This type stub file was generated by pyright.
"""

import numpy as np
from pathlib import Path
from typing import Any, Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import GallerySerializable
from PIL import Image as _Image
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Selectable

"""gr.Gallery() component."""
@document()
class Gallery(IOComponent, GallerySerializable, Selectable):
    """
    Used to display a list of images as a gallery that can be scrolled through.
    Preprocessing: this component does *not* accept input.
    Postprocessing: expects a list of images in any format, {List[numpy.array | PIL.Image | str | pathlib.Path]}, or a {List} of (image, {str} caption) tuples and displays them.

    Demos: fake_gan
    """
    def __init__(self, value: list[np.ndarray | _Image.Image | str | Path | tuple] | Callable | None = ..., *, label: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., columns: int | tuple | None = ..., rows: int | tuple | None = ..., height: int | float | None = ..., preview: bool | None = ..., object_fit: Literal["contain", "cover", "fill", "none", "scale-down"] | None = ..., allow_preview: bool = ..., show_share_button: bool | None = ..., show_download_button: bool | None = ..., **kwargs) -> None:
        """
        Parameters:
            value: List of images to display in the gallery by default. If callable, the function will be called whenever the app loads to set the initial value of the component.
            label: component name in interface.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            columns: Represents the number of images that should be shown in one row, for each of the six standard screen sizes (<576px, <768px, <992px, <1200px, <1400px, >1400px). if fewer that 6 are given then the last will be used for all subsequent breakpoints
            rows: Represents the number of rows in the image grid, for each of the six standard screen sizes (<576px, <768px, <992px, <1200px, <1400px, >1400px). if fewer that 6 are given then the last will be used for all subsequent breakpoints
            height: The height of the gallery component, in pixels. If more images are displayed than can fit in the height, a scrollbar will appear.
            preview: If True, will display the Gallery in preview mode, which shows all of the images as thumbnails and allows the user to click on them to view them in full size.
            object_fit: CSS object-fit property for the thumbnail images in the gallery. Can be "contain", "cover", "fill", "none", or "scale-down".
            allow_preview: If True, images in the gallery will be enlarged when they are clicked. Default is True.
            show_share_button: If True, will show a share icon in the corner of the component that allows user to share outputs to Hugging Face Spaces Discussions. If False, icon does not appear. If set to None (default behavior), then the icon appears if this Gradio app is launched on Spaces, but not otherwise.
            show_download_button: If True, will show a download button in the corner of the selected image. If False, the icon does not appear. Default is True.

        """
        ...
    
    @staticmethod
    def update(value: Any | Literal[_Keywords.NO_VALUE] | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ..., columns: int | tuple | None = ..., rows: int | tuple | None = ..., height: int | float | None = ..., preview: bool | None = ..., object_fit: Literal["contain", "cover", "fill", "none", "scale-down"] | None = ..., allow_preview: bool | None = ..., show_share_button: bool | None = ..., show_download_button: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def postprocess(self, y: list[np.ndarray | _Image.Image | str] | list[tuple[np.ndarray | _Image.Image | str, str]] | None) -> list[str]:
        """
        Parameters:
            y: list of images, or list of (image, caption) tuples
        Returns:
            list of string file paths to images in temp directory
        """
        ...
    
    def style(self, *, grid: int | tuple | None = ..., columns: int | tuple | None = ..., rows: int | tuple | None = ..., height: str | None = ..., container: bool | None = ..., preview: bool | None = ..., object_fit: str | None = ..., **kwargs): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


