"""
This type stub file was generated by pyright.
"""

from typing import Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import JSONSerializable
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Changeable, Selectable

"""gr.HighlightedText() component."""
@document()
class HighlightedText(Changeable, Selectable, IOComponent, JSONSerializable):
    """
    Displays text that contains spans that are highlighted by category or numerical value.
    Preprocessing: this component does *not* accept input.
    Postprocessing: expects a {List[Tuple[str, float | str]]]} consisting of spans of text and their associated labels, or a {Dict} with two keys: (1) "text" whose value is the complete text, and (2) "entities", which is a list of dictionaries, each of which have the keys: "entity" (consisting of the entity label, can alternatively be called "entity_group"), "start" (the character index where the label starts), and "end" (the character index where the label ends). Entities should not overlap.

    Demos: diff_texts, text_analysis
    Guides: named-entity-recognition
    """
    def __init__(self, value: list[tuple[str, str | float | None]] | dict | Callable | None = ..., *, color_map: dict[str, str] | None = ..., show_legend: bool = ..., combine_adjacent: bool = ..., adjacent_separator: str = ..., label: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., **kwargs) -> None:
        """
        Parameters:
            value: Default value to show. If callable, the function will be called whenever the app loads to set the initial value of the component.
            show_legend: whether to show span categories in a separate legend or inline.
            combine_adjacent: If True, will merge the labels of adjacent tokens belonging to the same category.
            adjacent_separator: Specifies the separator to be used between tokens if combine_adjacent is True.
            label: component name in interface.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: list[tuple[str, str | float | None]] | dict | Literal[_Keywords.NO_VALUE] | None = ..., color_map: dict[str, str] | None = ..., show_legend: bool | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def postprocess(self, y: list[tuple[str, str | float | None]] | dict | None) -> list[tuple[str, str | float | None]] | None:
        """
        Parameters:
            y: List of (word, category) tuples, or a dictionary of two keys: "text", and "entities", which itself is a list of dictionaries, each of which have the keys: "entity" (or "entity_group"), "start", and "end"
        Returns:
            List of (word, category) tuples
        """
        ...
    
    def style(self, *, color_map: dict[str, str] | None = ..., container: bool | None = ..., **kwargs): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


