"""
This type stub file was generated by pyright.
"""

import numpy as np
from pathlib import Path
from typing import Any, Literal
from gradio_client.documentation import document
from gradio_client.serializing import ImgSerializable
from PIL import Image as _Image
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Changeable, Clearable, Editable, Selectable, Streamable, Uploadable
from gradio.interpretation import TokenInterpretable

"""gr.Image() component."""
@document()
class Image(Editable, Clearable, Changeable, Streamable, Selectable, Uploadable, IOComponent, ImgSerializable, TokenInterpretable):
    """
    Creates an image component that can be used to upload/draw images (as an input) or display images (as an output).
    Preprocessing: passes the uploaded image as a {numpy.array}, {PIL.Image} or {str} filepath depending on `type` -- unless `tool` is `sketch` AND source is one of `upload` or `webcam`. In these cases, a {dict} with keys `image` and `mask` is passed, and the format of the corresponding values depends on `type`.
    Postprocessing: expects a {numpy.array}, {PIL.Image} or {str} or {pathlib.Path} filepath to an image and displays the image.
    Examples-format: a {str} filepath to a local file that contains the image.
    Demos: image_mod, image_mod_default_image
    Guides: image-classification-in-pytorch, image-classification-in-tensorflow, image-classification-with-vision-transformers, building-a-pictionary_app, create-your-own-friends-with-a-gan
    """
    def __init__(self, value: str | _Image.Image | np.ndarray | None = ..., *, shape: tuple[int, int] | None = ..., height: int | None = ..., width: int | None = ..., image_mode: Literal["1", "L", "P", "RGB", "RGBA", "CMYK", "YCbCr", "LAB", "HSV", "I", "F"] = ..., invert_colors: bool = ..., source: Literal["upload", "webcam", "canvas"] = ..., tool: Literal["editor", "select", "sketch", "color-sketch"] | None = ..., type: Literal["numpy", "pil", "filepath"] = ..., label: str | None = ..., every: float | None = ..., show_label: bool | None = ..., show_download_button: bool = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., mirror_webcam: bool = ..., brush_radius: float | None = ..., brush_color: str = ..., mask_opacity: float = ..., show_share_button: bool | None = ..., **kwargs) -> None:
        """
        Parameters:
            value: A PIL Image, numpy array, path or URL for the default value that Image component is going to take. If callable, the function will be called whenever the app loads to set the initial value of the component.
            shape: (width, height) shape to crop and resize image when passed to function. If None, matches input image size. Pass None for either width or height to only crop and resize the other.
            height: Height of the displayed image in pixels.
            width: Width of the displayed image in pixels.
            image_mode: "RGB" if color, or "L" if black and white. See https://pillow.readthedocs.io/en/stable/handbook/concepts.html for other supported image modes and their meaning.
            invert_colors: whether to invert the image as a preprocessing step.
            source: Source of image. "upload" creates a box where user can drop an image file, "webcam" allows user to take snapshot from their webcam, "canvas" defaults to a white image that can be edited and drawn upon with tools.
            tool: Tools used for editing. "editor" allows a full screen editor (and is the default if source is "upload" or "webcam"), "select" provides a cropping and zoom tool, "sketch" allows you to create a binary sketch (and is the default if source="canvas"), and "color-sketch" allows you to created a sketch in different colors. "color-sketch" can be used with source="upload" or "webcam" to allow sketching on an image. "sketch" can also be used with "upload" or "webcam" to create a mask over an image and in that case both the image and mask are passed into the function as a dictionary with keys "image" and "mask" respectively.
            type: The format the image is converted to before being passed into the prediction function. "numpy" converts the image to a numpy array with shape (height, width, 3) and values from 0 to 255, "pil" converts the image to a PIL image object, "filepath" passes a str path to a temporary file containing the image.
            label: component name in interface.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            show_download_button: If True, will display button to download image.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            interactive: if True, will allow users to upload and edit an image; if False, can only be used to display images. If not provided, this is inferred based on whether the component is used as an input or output.
            visible: If False, component will be hidden.
            streaming: If True when used in a `live` interface, will automatically stream webcam feed. Only valid is source is 'webcam'.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            mirror_webcam: If True webcam will be mirrored. Default is True.
            brush_radius: Size of the brush for Sketch. Default is None which chooses a sensible default
            brush_color: Color of the brush for Sketch as hex string. Default is "#000000".
            mask_opacity: Opacity of mask drawn on image, as a value between 0 and 1.
            show_share_button: If True, will show a share icon in the corner of the component that allows user to share outputs to Hugging Face Spaces Discussions. If False, icon does not appear. If set to None (default behavior), then the icon appears if this Gradio app is launched on Spaces, but not otherwise.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: Any | Literal[_Keywords.NO_VALUE] | None = ..., height: int | None = ..., width: int | None = ..., label: str | None = ..., show_label: bool | None = ..., show_download_button: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., interactive: bool | None = ..., visible: bool | None = ..., brush_radius: float | None = ..., brush_color: str | None = ..., mask_opacity: float | None = ..., show_share_button: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def preprocess(self, x: str | dict[str, str]) -> np.ndarray | _Image.Image | str | dict | None:
        """
        Parameters:
            x: base64 url data, or (if tool == "sketch") a dict of image and mask base64 url data
        Returns:
            image in requested format, or (if tool == "sketch") a dict of image and mask in requested format
        """
        ...
    
    def postprocess(self, y: np.ndarray | _Image.Image | str | Path | None) -> str | None:
        """
        Parameters:
            y: image as a numpy array, PIL Image, string/Path filepath, or string URL
        Returns:
            base64 url data
        """
        ...
    
    def set_interpret_parameters(self, segments: int = ...): # -> Self:
        """
        Calculates interpretation score of image subsections by splitting the image into subsections, then using a "leave one out" method to calculate the score of each subsection by whiting out the subsection and measuring the delta of the output value.
        Parameters:
            segments: Number of interpretation segments to split image into.
        """
        ...
    
    def tokenize(self, x): # -> tuple[list[Any], list[Any], list[Any]]:
        """
        Segments image into tokens, masks, and leave-one-out-tokens
        Parameters:
            x: base64 representation of an image
        Returns:
            tokens: list of tokens, used by the get_masked_input() method
            leave_one_out_tokens: list of left-out tokens, used by the get_interpretation_neighbors() method
            masks: list of masks, used by the get_interpretation_neighbors() method
        """
        ...
    
    def get_masked_inputs(self, tokens, binary_mask_matrix): # -> list[Any]:
        ...
    
    def get_interpretation_scores(self, x, neighbors, scores, masks, tokens=..., **kwargs) -> list[list[float]]:
        """
        Returns:
            A 2D array representing the interpretation score of each pixel of the image.
        """
        ...
    
    def style(self, *, height: int | None = ..., width: int | None = ..., **kwargs): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    
    def check_streamable(self): # -> None:
        ...
    
    def as_example(self, input_data: str | None) -> str:
        ...
    


