"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal
from gradio_client.documentation import document
from gradio_client.serializing import SimpleSerializable
from gradio.components.base import Component, _Keywords

"""gr.Interpretation() component"""
@document()
class Interpretation(Component, SimpleSerializable):
    """
    Used to create an interpretation widget for a component.
    Preprocessing: this component does *not* accept input.
    Postprocessing: expects a {dict} with keys "original" and "interpretation".

    Guides: custom-interpretations-with-blocks
    """
    def __init__(self, component: Component, *, visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., **kwargs) -> None:
        """
        Parameters:
            component: Which component to show in the interpretation widget.
            visible: Whether or not the interpretation is visible.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: Any | Literal[_Keywords.NO_VALUE] | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    


