"""
This type stub file was generated by pyright.
"""

from typing import Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import JSONSerializable
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Changeable, Selectable

"""gr.Label() component."""
@document()
class Label(Changeable, Selectable, IOComponent, JSONSerializable):
    """
    Displays a classification label, along with confidence scores of top categories, if provided.
    Preprocessing: this component does *not* accept input.
    Postprocessing: expects a {Dict[str, float]} of classes and confidences, or {str} with just the class or an {int}/{float} for regression outputs, or a {str} path to a .json file containing a json dictionary in the structure produced by Label.postprocess().

    Demos: main_note, titanic_survival
    Guides: image-classification-in-pytorch, image-classification-in-tensorflow, image-classification-with-vision-transformers, building-a-pictionary-app
    """
    CONFIDENCES_KEY = ...
    def __init__(self, value: dict[str, float] | str | float | Callable | None = ..., *, num_top_classes: int | None = ..., label: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., color: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            value: Default value to show in the component. If a str or number is provided, simply displays the string or number. If a {Dict[str, float]} of classes and confidences is provided, displays the top class on top and the `num_top_classes` below, along with their confidence bars. If callable, the function will be called whenever the app loads to set the initial value of the component.
            num_top_classes: number of most confident classes to show.
            label: component name in interface.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            color: The background color of the label (either a valid css color name or hexadecimal string).
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def postprocess(self, y: dict[str, float] | str | float | None) -> dict | None:
        """
        Parameters:
            y: a dictionary mapping labels to confidence value, or just a string/numerical label by itself
        Returns:
            Object with key 'label' representing primary label, and key 'confidences' representing a list of label-confidence pairs
        """
        ...
    
    @staticmethod
    def update(value: dict[str, float] | str | float | Literal[_Keywords.NO_VALUE] | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ..., color: str | Literal[_Keywords.NO_VALUE] | None = ...): # -> dict[str, Any]:
        ...
    
    def style(self, *, container: bool | None = ...): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


