"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Callable, Literal
from gradio_client.documentation import document
from gradio.components.base import _Keywords
from gradio.components.plot import Plot

"""gr.LinePlot() component"""
@document()
class LinePlot(Plot):
    """
    Create a line plot.

    Preprocessing: this component does *not* accept input.
    Postprocessing: expects a pandas dataframe with the data to plot.

    Demos: line_plot, live_dashboard
    """
    def __init__(self, value: pd.DataFrame | Callable | None = ..., x: str | None = ..., y: str | None = ..., *, color: str | None = ..., stroke_dash: str | None = ..., overlay_point: bool | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., stroke_dash_legend_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., stroke_dash_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., x_lim: list[int] | None = ..., y_lim: list[int] | None = ..., caption: str | None = ..., interactive: bool | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., every: float | None = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ...) -> None:
        """
        Parameters:
            value: The pandas dataframe containing the data to display in a scatter plot.
            x: Column corresponding to the x axis.
            y: Column corresponding to the y axis.
            color: The column to determine the point color. If the column contains numeric data, gradio will interpolate the column data so that small values correspond to light colors and large values correspond to dark values.
            stroke_dash: The column to determine the symbol used to draw the line, e.g. dashed lines, dashed lines with points.
            overlay_point: Whether to draw a point on the line for each (x, y) coordinate pair.
            title: The title to display on top of the chart.
            tooltip: The column (or list of columns) to display on the tooltip when a user hovers a point on the plot.
            x_title: The title given to the x axis. By default, uses the value of the x parameter.
            y_title: The title given to the y axis. By default, uses the value of the y parameter.
            x_label_angle: The angle for the x axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            y_label_angle: The angle for the y axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            color_legend_title: The title given to the color legend. By default, uses the value of color parameter.
            stroke_dash_legend_title: The title given to the stroke_dash legend. By default, uses the value of the stroke_dash parameter.
            color_legend_position: The position of the color legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            stroke_dash_legend_position: The position of the stoke_dash legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            height: The height of the plot in pixels.
            width: The width of the plot in pixels.
            x_lim: A tuple or list containing the limits for the x-axis, specified as [x_min, x_max].
            y_lim: A tuple of list containing the limits for the y-axis, specified as [y_min, y_max].
            caption: The (optional) caption to display below the plot.
            interactive: Whether users should be able to interact with the plot by panning or zooming with their mouse or trackpad.
            label: The (optional) label to display on the top left corner of the plot.
            show_label: Whether the label should be displayed.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            visible: Whether the plot should be visible.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def get_block_name(self) -> str:
        ...
    
    @staticmethod
    def update(value: pd.DataFrame | dict | Literal[_Keywords.NO_VALUE] = ..., x: str | None = ..., y: str | None = ..., color: str | None = ..., stroke_dash: str | None = ..., overlay_point: bool | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., stroke_dash_legend_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., stroke_dash_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., x_lim: list[int] | None = ..., y_lim: list[int] | None = ..., interactive: bool | None = ..., caption: str | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        """Update an existing plot component.

        If updating any of the plot properties (color, size, etc) the value, x, and y parameters must be specified.

        Parameters:
            value: The pandas dataframe containing the data to display in a scatter plot.
            x: Column corresponding to the x axis.
            y: Column corresponding to the y axis.
            color: The column to determine the point color. If the column contains numeric data, gradio will interpolate the column data so that small values correspond to light colors and large values correspond to dark values.
            stroke_dash: The column to determine the symbol used to draw the line, e.g. dashed lines, dashed lines with points.
            overlay_point: Whether to draw a point on the line for each (x, y) coordinate pair.
            title: The title to display on top of the chart.
            tooltip: The column (or list of columns) to display on the tooltip when a user hovers a point on the plot.
            x_title: The title given to the x axis. By default, uses the value of the x parameter.
            y_title: The title given to the y axis. By default, uses the value of the y parameter.
            x_label_angle:  The angle for the x axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            y_label_angle:  The angle for the y axis labels. Positive values are clockwise, and negative values are counter-clockwise.
            color_legend_title: The title given to the color legend. By default, uses the value of color parameter.
            stroke_dash_legend_title: The title given to the stroke legend. By default, uses the value of stroke parameter.
            color_legend_position: The position of the color legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation
            stroke_dash_legend_position: The position of the stoke_dash legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation
            height: The height of the plot in pixels.
            width: The width of the plot in pixels.
            x_lim: A tuple or list containing the limits for the x-axis, specified as [x_min, x_max].
            y_lim: A tuple of list containing the limits for the y-axis, specified as [y_min, y_max].
            caption: The (optional) caption to display below the plot.
            interactive: Whether users should be able to interact with the plot by panning or zooming with their mouse or trackpad.
            label: The (optional) label to display in the top left corner of the plot.
            show_label: Whether the label should be displayed.
            visible: Whether the plot should be visible.
        """
        ...
    
    @staticmethod
    def create_plot(value: pd.DataFrame, x: str, y: str, color: str | None = ..., stroke_dash: str | None = ..., overlay_point: bool | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., stroke_dash_legend_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., stroke_dash_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., x_lim: list[int] | None = ..., y_lim: list[int] | None = ..., interactive: bool | None = ...): # -> LayerChart:
        """Helper for creating the scatter plot."""
        ...
    
    def postprocess(self, y: pd.DataFrame | dict | None) -> dict[str, str] | None:
        ...
    


