"""
This type stub file was generated by pyright.
"""

from typing import Literal
from gradio_client.documentation import document
from gradio.components import Button

"""Predefined button to sign in with Hugging Face in a Gradio Space."""
@document()
class LoginButton(Button):
    """
    Button that redirects the user to Sign with Hugging Face using OAuth.
    """
    is_template = ...
    def __init__(self, *, value: str = ..., variant: Literal["primary", "secondary", "stop"] = ..., size: Literal["sm", "lg"] | None = ..., icon: str | None = ..., link: str | None = ..., visible: bool = ..., interactive: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., scale: int | None = ..., min_width: int | None = ..., **kwargs) -> None:
        ...
    
    def activate(self): # -> None:
        ...
    


_js_open_if_not_logged_in = ...
