"""
This type stub file was generated by pyright.
"""

from typing import Literal
from gradio_client.documentation import document
from gradio.components import Button

"""Predefined button to sign out from Hugging Face in a Gradio Space."""
@document()
class LogoutButton(Button):
    """
    Button to log out a user from a Space.
    """
    is_template = ...
    def __init__(self, *, value: str = ..., variant: Literal["primary", "secondary", "stop"] = ..., size: Literal["sm", "lg"] | None = ..., icon: str | None = ..., link: str | None = ..., visible: bool = ..., interactive: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., scale: int | None = ..., min_width: int | None = ..., **kwargs) -> None:
        ...
    


