"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import JSONSerializable
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Changeable, Clearable

"""gr.Plot() component."""
@document()
class Plot(Changeable, Clearable, IOComponent, JSONSerializable):
    """
    Used to display various kinds of plots (matplotlib, plotly, or bokeh are supported)
    Preprocessing: this component does *not* accept input.
    Postprocessing: expects either a {matplotlib.figure.Figure}, a {plotly.graph_objects._figure.Figure}, or a {dict} corresponding to a bokeh plot (json_item format)

    Demos: altair_plot, outbreak_forecast, blocks_kinematics, stock_forecast, map_airbnb
    Guides: plot-component-for-maps
    """
    def __init__(self, value: Callable | None | pd.DataFrame = ..., *, label: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., **kwargs) -> None:
        """
        Parameters:
            value: Optionally, supply a default plot object to display, must be a matplotlib, plotly, altair, or bokeh figure, or a callable. If callable, the function will be called whenever the app loads to set the initial value of the component.
            label: component name in interface.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: Any | Literal[_Keywords.NO_VALUE] | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def postprocess(self, y) -> dict[str, str] | None:
        """
        Parameters:
            y: plot data
        Returns:
            plot type mapped to plot base64 data
        """
        ...
    
    def style(self, container: bool | None = ...): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


class AltairPlot:
    @staticmethod
    def create_legend(position, title): # -> dict[str, Any] | None:
        ...
    
    @staticmethod
    def create_scale(limit): # -> Scale | UndefinedType:
        ...
    


