"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import StringSerializable
from gradio.components.base import FormComponent, IOComponent, _Keywords
from gradio.events import Changeable, Inputable, Selectable
from gradio.interpretation import NeighborInterpretable

"""gr.Radio() component."""
@document()
class Radio(FormComponent, Selectable, Changeable, Inputable, IOComponent, StringSerializable, NeighborInterpretable):
    """
    Creates a set of (string or numeric type) radio buttons of which only one can be selected.
    Preprocessing: passes the value of the selected radio button as a {str} or {int} or {float} or its index as an {int} into the function, depending on `type`.
    Postprocessing: expects a {str} or {int} or {float} corresponding to the value of the radio button to be selected.
    Examples-format: a {str} representing the radio option to select.

    Demos: sentence_builder, titanic_survival, blocks_essay
    """
    def __init__(self, choices: list[str | int | float | tuple[str, str | int | float]] | None = ..., *, value: str | int | float | Callable | None = ..., type: str = ..., label: str | None = ..., info: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., **kwargs) -> None:
        """
        Parameters:
            choices: A list of string or numeric options to select from. An option can also be a tuple of the form (name, value), where name is the displayed name of the radio button and value is the value to be passed to the function, or returned by the function.
            value: The option selected by default. If None, no option is selected by default. If callable, the function will be called whenever the app loads to set the initial value of the component.
            type: Type of value to be returned by component. "value" returns the string of the choice selected, "index" returns the index of the choice selected.
            label: Component name in interface.
            info: Additional component description.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: Relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: Minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            interactive: If True, choices in this radio group will be selectable; if False, selection will be disabled. If not provided, this is inferred based on whether the component is used as an input or output.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def example_inputs(self) -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: str | int | float | Literal[_Keywords.NO_VALUE] | None = ..., choices: list[str | int | float | tuple[str, str | int | float]] | None = ..., label: str | None = ..., info: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., interactive: bool | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def preprocess(self, x: str | int | float | None) -> str | int | float | None:
        """
        Parameters:
            x: selected choice
        Returns:
            value of the selected choice as string or index within choice list
        """
        ...
    
    def get_interpretation_neighbors(self, x): # -> tuple[list[str | int | float], dict[Any, Any]]:
        ...
    
    def get_interpretation_scores(self, x, neighbors, scores: list[float | None], **kwargs) -> list:
        """
        Returns:
            Each value represents the interpretation score corresponding to each choice.
        """
        ...
    
    def style(self, *, item_container: bool | None = ..., container: bool | None = ..., **kwargs): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    
    def as_example(self, input_data): # -> str | None:
        ...
    


