"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Callable, Literal
from gradio_client.documentation import document
from gradio.components.base import _Keywords
from gradio.components.plot import Plot

"""gr.ScatterPlot() component."""
@document()
class ScatterPlot(Plot):
    """
    Create a scatter plot.

    Preprocessing: this component does *not* accept input.
    Postprocessing: expects a pandas dataframe with the data to plot.

    Demos: scatter_plot
    Guides: creating-a-dashboard-from-bigquery-data
    """
    def __init__(self, value: pd.DataFrame | Callable | None = ..., x: str | None = ..., y: str | None = ..., *, color: str | None = ..., size: str | None = ..., shape: str | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., size_legend_title: str | None = ..., shape_legend_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., size_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., shape_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., x_lim: list[int | float] | None = ..., y_lim: list[int | float] | None = ..., caption: str | None = ..., interactive: bool | None = ..., label: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ...) -> None:
        """
        Parameters:
            value: The pandas dataframe containing the data to display in a scatter plot, or a callable. If callable, the function will be called whenever the app loads to set the initial value of the component.
            x: Column corresponding to the x axis.
            y: Column corresponding to the y axis.
            color: The column to determine the point color. If the column contains numeric data, gradio will interpolate the column data so that small values correspond to light colors and large values correspond to dark values.
            size: The column used to determine the point size. Should contain numeric data so that gradio can map the data to the point size.
            shape: The column used to determine the point shape. Should contain categorical data. Gradio will map each unique value to a different shape.
            title: The title to display on top of the chart.
            tooltip: The column (or list of columns) to display on the tooltip when a user hovers a point on the plot.
            x_title: The title given to the x-axis. By default, uses the value of the x parameter.
            y_title: The title given to the y-axis. By default, uses the value of the y parameter.
            x_label_angle:  The angle for the x axis labels rotation. Positive values are clockwise, and negative values are counter-clockwise.
            y_label_angle:  The angle for the y axis labels rotation. Positive values are clockwise, and negative values are counter-clockwise.
            color_legend_title: The title given to the color legend. By default, uses the value of color parameter.
            size_legend_title: The title given to the size legend. By default, uses the value of the size parameter.
            shape_legend_title: The title given to the shape legend. By default, uses the value of the shape parameter.
            color_legend_position: The position of the color legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            size_legend_position: The position of the size legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            shape_legend_position: The position of the shape legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            height: The height of the plot in pixels.
            width: The width of the plot in pixels.
            x_lim: A tuple or list containing the limits for the x-axis, specified as [x_min, x_max].
            y_lim: A tuple of list containing the limits for the y-axis, specified as [y_min, y_max].
            caption: The (optional) caption to display below the plot.
            interactive: Whether users should be able to interact with the plot by panning or zooming with their mouse or trackpad.
            label: The (optional) label to display on the top left corner of the plot.
            every:  If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: Whether the label should be displayed.
            visible: Whether the plot should be visible.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def get_block_name(self) -> str:
        ...
    
    @staticmethod
    def update(value: pd.DataFrame | dict | Literal[_Keywords.NO_VALUE] = ..., x: str | None = ..., y: str | None = ..., color: str | None = ..., size: str | None = ..., shape: str | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., size_legend_title: str | None = ..., shape_legend_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., size_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., shape_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., x_lim: list[int | float] | None = ..., y_lim: list[int | float] | None = ..., interactive: bool | None = ..., caption: str | None = ..., label: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        """Update an existing plot component.

        If updating any of the plot properties (color, size, etc) the value, x, and y parameters must be specified.

        Parameters:
            value: The pandas dataframe containing the data to display in a scatter plot.
            x: Column corresponding to the x axis.
            y: Column corresponding to the y axis.
            color: The column to determine the point color. If the column contains numeric data, gradio will interpolate the column data so that small values correspond to light colors and large values correspond to dark values.
            size: The column used to determine the point size. Should contain numeric data so that gradio can map the data to the point size.
            shape: The column used to determine the point shape. Should contain categorical data. Gradio will map each unique value to a different shape.
            title: The title to display on top of the chart.
            tooltip: The column (or list of columns) to display on the tooltip when a user hovers a point on the plot.
            x_title: The title given to the x axis. By default, uses the value of the x parameter.
            y_title: The title given to the y axis. By default, uses the value of the y parameter.
            x_label_angle:  The angle for the x axis labels rotation. Positive values are clockwise, and negative values are counter-clockwise.
            y_label_angle:  The angle for the y axis labels rotation. Positive values are clockwise, and negative values are counter-clockwise.
            color_legend_title: The title given to the color legend. By default, uses the value of color parameter.
            size_legend_title: The title given to the size legend. By default, uses the value of the size parameter.
            shape_legend_title: The title given to the shape legend. By default, uses the value of the shape parameter.
            color_legend_position: The position of the color legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            size_legend_position: The position of the size legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            shape_legend_position: The position of the shape legend. If the string value 'none' is passed, this legend is omitted. For other valid position values see: https://vega.github.io/vega/docs/legends/#orientation.
            height: The height of the plot in pixels.
            width: The width of the plot in pixels.
            x_lim: A tuple or list containing the limits for the x-axis, specified as [x_min, x_max].
            y_lim: A tuple of list containing the limits for the y-axis, specified as [y_min, y_max].
            interactive: Whether users should be able to interact with the plot by panning or zooming with their mouse or trackpad.
            caption: The (optional) caption to display below the plot.
            label: The (optional) label to display in the top left corner of the plot.
            show_label: Whether the label should be displayed.
            visible: Whether the plot should be visible.
        """
        ...
    
    @staticmethod
    def create_plot(value: pd.DataFrame, x: str, y: str, color: str | None = ..., size: str | None = ..., shape: str | None = ..., title: str | None = ..., tooltip: list[str] | str | None = ..., x_title: str | None = ..., y_title: str | None = ..., x_label_angle: float | None = ..., y_label_angle: float | None = ..., color_legend_title: str | None = ..., size_legend_title: str | None = ..., shape_legend_title: str | None = ..., color_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., size_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., shape_legend_position: Literal["left", "right", "top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right", "none",] | None = ..., height: int | None = ..., width: int | None = ..., x_lim: list[int | float] | None = ..., y_lim: list[int | float] | None = ..., interactive: bool | None = ...): # -> Chart:
        """Helper for creating the scatter plot."""
        ...
    
    def postprocess(self, y: pd.DataFrame | dict | None) -> dict[str, str] | None:
        ...
    


