"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import NumberSerializable
from gradio.components.base import FormComponent, IOComponent, _Keywords
from gradio.events import Changeable, Inputable, Releaseable
from gradio.interpretation import NeighborInterpretable

"""gr.Slider() component."""
@document()
class Slider(FormComponent, Changeable, Inputable, Releaseable, IOComponent, NumberSerializable, NeighborInterpretable):
    """
    Creates a slider that ranges from `minimum` to `maximum` with a step size of `step`.
    Preprocessing: passes slider value as a {float} into the function.
    Postprocessing: expects an {int} or {float} returned from function and sets slider value to it as long as it is within range.
    Examples-format: A {float} or {int} representing the slider's value.

    Demos: sentence_builder, slider_release, generate_tone, titanic_survival, interface_random_slider, blocks_random_slider
    Guides: create-your-own-friends-with-a-gan
    """
    def __init__(self, minimum: float = ..., maximum: float = ..., value: float | Callable | None = ..., *, step: float | None = ..., label: str | None = ..., info: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., randomize: bool = ..., **kwargs) -> None:
        """
        Parameters:
            minimum: minimum value for slider.
            maximum: maximum value for slider.
            value: default value. If callable, the function will be called whenever the app loads to set the initial value of the component. Ignored if randomized=True.
            step: increment between slider values.
            label: component name in interface.
            info: additional component description.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            interactive: if True, slider will be adjustable; if False, adjusting will be disabled. If not provided, this is inferred based on whether the component is used as an input or output.
            visible: If False, component will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            randomize: If True, the value of the slider when the app loads is taken uniformly at random from the range given by the minimum and maximum.
        """
        ...
    
    def api_info(self) -> dict[str, dict | bool]:
        ...
    
    def example_inputs(self) -> dict[str, Any]:
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def get_random_value(self): # -> float | Any:
        ...
    
    @staticmethod
    def update(value: float | Literal[_Keywords.NO_VALUE] | None = ..., minimum: float | None = ..., maximum: float | None = ..., step: float | None = ..., label: str | None = ..., info: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., interactive: bool | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def postprocess(self, y: float | None) -> float | None:
        """
        Any postprocessing needed to be performed on function output.
        Parameters:
            y: numeric output
        Returns:
            numeric output or minimum number if None
        """
        ...
    
    def set_interpret_parameters(self, steps: int = ...) -> Slider:
        """
        Calculates interpretation scores of numeric values ranging between the minimum and maximum values of the slider.
        Parameters:
            steps: Number of neighboring values to measure between the minimum and maximum values of the slider range.
        """
        ...
    
    def get_interpretation_neighbors(self, x) -> tuple[object, dict]:
        ...
    
    def style(self, *, container: bool | None = ...): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


