"""
This type stub file was generated by pyright.
"""

from gradio_client.serializing import SimpleSerializable
from gradio.components.base import Component

"""gr.StatusTracker() component."""
class StatusTracker(Component, SimpleSerializable):
    def __init__(self, **kwargs) -> None:
        ...
    


