"""
This type stub file was generated by pyright.
"""

from typing import Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import StringSerializable
from gradio.components.base import FormComponent, IOComponent, _Keywords
from gradio.events import Changeable, Focusable, Inputable, Selectable, Submittable
from gradio.interpretation import TokenInterpretable

"""gr.Textbox() component."""
@document()
class Textbox(FormComponent, Changeable, Inputable, Selectable, Submittable, Focusable, IOComponent, StringSerializable, TokenInterpretable):
    """
    Creates a textarea for user to enter string input or display string output.
    Preprocessing: passes textarea value as a {str} into the function.
    Postprocessing: expects a {str} returned from function and sets textarea value to it.
    Examples-format: a {str} representing the textbox input.

    Demos: hello_world, diff_texts, sentence_builder
    Guides: creating-a-chatbot, real-time-speech-recognition
    """
    def __init__(self, value: str | Callable | None = ..., *, lines: int = ..., max_lines: int = ..., placeholder: str | None = ..., label: str | None = ..., info: str | None = ..., every: float | None = ..., show_label: bool | None = ..., container: bool = ..., scale: int | None = ..., min_width: int = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., autofocus: bool = ..., elem_classes: list[str] | str | None = ..., type: Literal["text", "password", "email"] = ..., text_align: Literal["left", "right"] | None = ..., rtl: bool = ..., show_copy_button: bool = ..., **kwargs) -> None:
        """
        Parameters:
            value: default text to provide in textarea. If callable, the function will be called whenever the app loads to set the initial value of the component.
            lines: minimum number of line rows to provide in textarea.
            max_lines: maximum number of line rows to provide in textarea.
            placeholder: placeholder hint to provide behind textarea.
            label: component name in interface.
            info: additional component description.
            every: If `value` is a callable, run the function 'every' number of seconds while the client connection is open. Has no effect otherwise. Queue must be enabled. The event can be accessed (e.g. to cancel it) via this component's .load_event attribute.
            show_label: if True, will display label.
            container: If True, will place the component in a container - providing some extra padding around the border.
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            interactive: if True, will be rendered as an editable textbox; if False, editing will be disabled. If not provided, this is inferred based on whether the component is used as an input or output.
            visible: If False, component will be hidden.
            autofocus: If True, will focus on the textbox when the page loads.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            type: The type of textbox. One of: 'text', 'password', 'email', Default is 'text'.
            text_align: How to align the text in the textbox, can be: "left", "right", or None (default). If None, the alignment is left if `rtl` is False, or right if `rtl` is True. Can only be changed if `type` is "text".
            rtl: If True and `type` is "text", sets the direction of the text to right-to-left (cursor appears on the left of the text). Default is False, which renders cursor on the right.
            show_copy_button: If True, includes a copy button to copy the text in the textbox. Only applies if show_label is True.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: str | Literal[_Keywords.NO_VALUE] | None = ..., lines: int | None = ..., max_lines: int | None = ..., placeholder: str | None = ..., label: str | None = ..., info: str | None = ..., show_label: bool | None = ..., container: bool | None = ..., scale: int | None = ..., min_width: int | None = ..., visible: bool | None = ..., interactive: bool | None = ..., type: Literal["text", "password", "email"] | None = ..., text_align: Literal["left", "right"] | None = ..., rtl: bool | None = ..., show_copy_button: bool | None = ..., autofocus: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def preprocess(self, x: str | None) -> str | None:
        """
        Preprocesses input (converts it to a string) before passing it to the function.
        Parameters:
            x: text
        Returns:
            text
        """
        ...
    
    def postprocess(self, y: str | None) -> str | None:
        """
        Postproccess the function output y by converting it to a str before passing it to the frontend.
        Parameters:
            y: function output to postprocess.
        Returns:
            text
        """
        ...
    
    def set_interpret_parameters(self, separator: str = ..., replacement: str | None = ...): # -> Self:
        """
        Calculates interpretation score of characters in input by splitting input into tokens, then using a "leave one out" method to calculate the score of each token by removing each token and measuring the delta of the output value.
        Parameters:
            separator: Separator to use to split input into tokens.
            replacement: In the "leave one out" step, the text that the token should be replaced with. If None, the token is removed altogether.
        """
        ...
    
    def tokenize(self, x: str) -> tuple[list[str], list[str], None]:
        """
        Tokenizes an input string by dividing into "words" delimited by self.interpretation_separator
        """
        ...
    
    def get_masked_inputs(self, tokens: list[str], binary_mask_matrix: list[list[int]]) -> list[str]:
        """
        Constructs partially-masked sentences for SHAP interpretation
        """
        ...
    
    def get_interpretation_scores(self, x, neighbors, scores: list[float], tokens: list[str], masks=..., **kwargs) -> list[tuple[str, float]]:
        """
        Returns:
            Each tuple set represents a set of characters and their corresponding interpretation score.
        """
        ...
    
    def style(self, *, show_copy_button: bool | None = ..., container: bool | None = ..., **kwargs): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


