"""
This type stub file was generated by pyright.
"""

import tempfile
from typing import Any, Callable, Literal
from gradio_client.documentation import document
from gradio_client.serializing import FileSerializable
from gradio.components.base import IOComponent, _Keywords
from gradio.events import Clickable, Uploadable

"""gr.UploadButton() component."""
@document()
class UploadButton(Clickable, Uploadable, IOComponent, FileSerializable):
    """
    Used to create an upload button, when cicked allows a user to upload files that satisfy the specified file type or generic files (if file_type not set).
    Preprocessing: passes the uploaded file as a {file-object} or {List[file-object]} depending on `file_count` (or a {bytes}/{List{bytes}} depending on `type`)
    Postprocessing: expects function to return a {str} path to a file, or {List[str]} consisting of paths to files.
    Examples-format: a {str} path to a local file that populates the component.
    Demos: upload_button
    """
    def __init__(self, label: str = ..., value: str | list[str] | Callable | None = ..., *, variant: Literal["primary", "secondary", "stop"] = ..., visible: bool = ..., size: Literal["sm", "lg"] | None = ..., scale: int | None = ..., min_width: int | None = ..., interactive: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., type: Literal["file", "bytes"] = ..., file_count: Literal["single", "multiple", "directory"] = ..., file_types: list[str] | None = ..., **kwargs) -> None:
        """
        Parameters:
            label: Text to display on the button. Defaults to "Upload a File".
            value: File or list of files to upload by default.
            variant: 'primary' for main call-to-action, 'secondary' for a more subdued style, 'stop' for a stop button.
            visible: If False, component will be hidden.
            size: Size of the button. Can be "sm" or "lg".
            scale: relative width compared to adjacent Components in a Row. For example, if Component A has scale=2, and Component B has scale=1, A will be twice as wide as B. Should be an integer.
            min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
            interactive: If False, the UploadButton will be in a disabled state.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            elem_classes: An optional list of strings that are assigned as the classes of this component in the HTML DOM. Can be used for targeting CSS styles.
            type: Type of value to be returned by component. "file" returns a temporary file object with the same base name as the uploaded file, whose full path can be retrieved by file_obj.name, "binary" returns an bytes object.
            file_count: if single, allows user to upload one file. If "multiple", user uploads multiple files. If "directory", user uploads all files in selected directory. Return type will be list for each file in case of "multiple" or "directory".
            file_types: List of type of files to be uploaded. "file" allows any file to be uploaded, "image" allows only image files to be uploaded, "audio" allows only audio files to be uploaded, "video" allows only video files to be uploaded, "text" allows only text files to be uploaded.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(value: str | list[str] | Literal[_Keywords.NO_VALUE] | None = ..., label: str | None = ..., size: Literal["sm", "lg"] | None = ..., variant: Literal["primary", "secondary", "stop"] | None = ..., interactive: bool | None = ..., visible: bool | None = ..., scale: int | None = ..., min_width: int | None = ...): # -> dict[str, Any]:
        ...
    
    def preprocess(self, x: list[dict[str, Any]] | None) -> (bytes | tempfile._TemporaryFileWrapper | list[bytes | tempfile._TemporaryFileWrapper] | None):
        """
        Parameters:
            x: List of JSON objects with filename as 'name' property and base64 data as 'data' property
        Returns:
            File objects in requested format
        """
        ...
    
    def style(self, *, full_width: bool | None = ..., size: Literal["sm", "lg"] | None = ..., **kwargs): # -> Self:
        """
        This method is deprecated. Please set these arguments in the constructor instead.
        """
        ...
    


