-- imports MUST precede all content in Lean 4
import SureGPU.Types
import SureGPU.Lifespan
import SureGPU.Stream
import SureGPU.Transfer
import SureGPU.SURE

/-!
# SureGPU — Lean 4 Formalization of SURE Optimization on GPU

This library formalizes the GPU execution of the SURE (Stein's Unbiased Risk
Estimator) computation, focusing on three concerns:

1. **Information lifespan** — every device buffer's active interval is precisely
   characterized, and it is proved tight (freed on the step after last use).

2. **Parallelism** — CUDA stream independence is modelled; two parallel pairs
   are identified and proved correct (`genB ∥ denoiser1`, `computeGrad ∥ d2hSURE`).

3. **Transfer policy** — every Host↔Device transfer is categorized;
   it is proved that the Hutchinson probe `b` (generated by cuRAND on-device)
   and the SURE gradient (consumed by the Langevin update on-device) need no PCIe
   transfer.  The sole D2H is the 4-byte SURE scalar, run asynchronously on stream S3.

## Module structure

```
SureGPU/
  Types.lean    — Core types: MemLoc, StreamId, Buffer, Span, Op
  Lifespan.lean — Buffer lifespan theory; tight spans; memory-sharing pairs
  Stream.lean   — CUDA stream model; concurrency predicate; schedule correctness
  Transfer.lean — H2D/D2H classification; async overlap; transfer-optimality
  SURE.lean     — Master integration theorem collecting all results
```

## Master result

`SureGPU.sure_full_schedule_theorem` proves (A)–(H) simultaneously:

  (A) The data-dependency graph of SURE is acyclic.
  (B) All ordering constraints are satisfied.
  (C) Latency = 7 (< serial lower bound 8), achieved by two concurrent pairs.
  (D) No H2D transfer for b (cuRAND on-device).
  (E) No D2H transfer for the gradient (Langevin update on-device).
  (F) The sole D2H is the 4-byte SURE scalar, running asynchronously on S3.
  (G) All buffers are freed immediately after last use (zero wasted device memory).
  (H) Three pairs of buffers can share one device allocation.

## Relationship to SGPSFull (algebraic SURE proofs)

The algebraic correctness of SURE — that E[SURE] = MSE, that Hutchinson is
unbiased, that sigma-bias is bounded — is proved in `lean_proofs/SGPSProofs/Full.lean`
(the `SGPSFull` namespace).  This library proves the complementary claim: the GPU
schedule that evaluates those formulas is valid, parallel, and transfer-optimal.
-/
