"""
This type stub file was generated by pyright.
"""

import gradio
from typing import Any

""" Functions related to analytics and telemetry. """
ANALYTICS_URL = ...
PKG_VERSION_URL = ...
def analytics_enabled() -> bool:
    """
    Returns: True if analytics are enabled, False otherwise.
    """
    ...

def version_check(): # -> None:
    ...

def get_local_ip_address() -> str:
    """
    Gets the public IP address or returns the string "No internet connection" if unable
    to obtain it or the string "Analytics disabled" if a user has disabled analytics.
    Does not make a new request if the IP address has already been obtained in the
    same Python session.
    """
    ...

async def get_local_ip_address_wasm() -> str:
    """The Wasm-compatible version of get_local_ip_address()."""
    ...

def initiated_analytics(data: dict[str, Any]) -> None:
    ...

def launched_analytics(blocks: gradio.Blocks, data: dict[str, Any]) -> None:
    ...

def integration_analytics(data: dict[str, Any]) -> None:
    ...

def error_analytics(message: str) -> None:
    """
    Send error analytics if there is network
    Parameters:
        message: Details about error
    """
    ...

