"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from types import ModuleType
from typing import Any, AsyncIterator, Callable, Literal, TYPE_CHECKING
from gradio_client.documentation import document
from gradio import routes
from gradio.helpers import EventData
from gradio.themes import ThemeClass as Theme
from gradio.utils import concurrency_count_warning
from fastapi.applications import FastAPI
from gradio.components import Component

if TYPE_CHECKING:
    ...
BUILT_IN_THEMES: dict[str, Theme] = ...
class Block:
    def __init__(self, *, render: bool = ..., elem_id: str | None = ..., elem_classes: list[str] | str | None = ..., visible: bool = ..., root_url: str | None = ..., _skip_init_processing: bool = ..., **kwargs) -> None:
        ...
    
    def render(self): # -> IOComponent | Block | Self:
        """
        Adds self into appropriate BlockContext
        """
        ...
    
    def unrender(self): # -> Self:
        """
        Removes self from BlockContext if it has been rendered (otherwise does nothing).
        Removes self from the layout and collection of blocks, but does not delete any event triggers.
        """
        ...
    
    def get_block_name(self) -> str:
        """
        Gets block's class name.

        If it is template component it gets the parent's class name.

        @return: class name
        """
        ...
    
    def get_expected_parent(self) -> type[BlockContext] | None:
        ...
    
    def set_event_trigger(self, event_name: str, fn: Callable | None, inputs: Component | list[Component] | set[Component] | None, outputs: Component | list[Component] | None, preprocess: bool = ..., postprocess: bool = ..., scroll_to_output: bool = ..., show_progress: str = ..., api_name: str | None | Literal[False] = ..., js: str | None = ..., no_target: bool = ..., queue: bool | None = ..., batch: bool = ..., max_batch_size: int = ..., cancels: list[int] | None = ..., every: float | None = ..., collects_event_data: bool | None = ..., trigger_after: int | None = ..., trigger_only_on_success: bool = ...) -> tuple[dict[str, Any], int]:
        """
        Adds an event to the component's dependencies.
        Parameters:
            event_name: event name
            fn: Callable function
            inputs: input list
            outputs: output list
            preprocess: whether to run the preprocess methods of components
            postprocess: whether to run the postprocess methods of components
            scroll_to_output: whether to scroll to output of dependency on trigger
            show_progress: whether to show progress animation while running.
            api_name: defines how the endpoint appears in the API docs. Can be a string, None, or False. If False, the endpoint will not be exposed in the api docs. If set to None, the endpoint will be exposed in the api docs as an unnamed endpoint, although this behavior will be changed in Gradio 4.0. If set to a string, the endpoint will be exposed in the api docs with the given name.
            js: Experimental parameter (API may change): Optional frontend js method to run before running 'fn'. Input arguments for js method are values of 'inputs' and 'outputs', return should be a list of values for output components
            no_target: if True, sets "targets" to [], used for Blocks "load" event
            queue: If True, will place the request on the queue, if the queue has been enabled. If False, will not put this event on the queue, even if the queue has been enabled. If None, will use the queue setting of the gradio app.
            batch: whether this function takes in a batch of inputs
            max_batch_size: the maximum batch size to send to the function
            cancels: a list of other events to cancel when this event is triggered. For example, setting cancels=[click_event] will cancel the click_event, where click_event is the return value of another components .click method.
            every: Run this event 'every' number of seconds while the client connection is open. Interpreted in seconds. Queue must be enabled.
            collects_event_data: whether to collect event data for this event
            trigger_after: if set, this event will be triggered after 'trigger_after' function index
            trigger_only_on_success: if True, this event will only be triggered if the previous event was successful (only applies if `trigger_after` is set)
        Returns: dependency information, dependency index
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    @abstractmethod
    def update(**kwargs) -> dict:
        ...
    
    @classmethod
    def get_specific_update(cls, generic_update: dict[str, Any]) -> dict:
        ...
    


class BlockContext(Block):
    def __init__(self, visible: bool = ..., render: bool = ..., **kwargs) -> None:
        """
        Parameters:
            visible: If False, this will be hidden but included in the Blocks config file (its visibility can later be updated).
            render: If False, this will not be included in the Blocks config file at all.
        """
        ...
    
    def add_child(self, child: Block): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def add(self, child: Block): # -> None:
        ...
    
    def fill_expected_parents(self): # -> None:
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None = ..., *args): # -> None:
        ...
    
    def postprocess(self, y):
        """
        Any postprocessing needed to be performed on a block context.
        """
        ...
    


class BlockFunction:
    def __init__(self, fn: Callable | None, inputs: list[Component], outputs: list[Component], preprocess: bool, postprocess: bool, inputs_as_dict: bool, tracks_progress: bool = ...) -> None:
        ...
    
    def spaces_auto_wrap(self): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    


def postprocess_update_dict(block: Block, update_dict: dict, postprocess: bool = ...): # -> dict[Any, Any]:
    """
    Converts a dictionary of updates into a format that can be sent to the frontend.
    E.g. {"__type__": "generic_update", "value": "2", "interactive": False}
    Into -> {"__type__": "update", "value": 2.0, "mode": "static"}

    Parameters:
        block: The Block that is being updated with this update dictionary.
        update_dict: The original update dictionary
        postprocess: Whether to postprocess the "value" key of the update dictionary.
    """
    ...

def convert_component_dict_to_list(outputs_ids: list[int], predictions: dict) -> list | dict:
    """
    Converts a dictionary of component updates into a list of updates in the order of
    the outputs_ids and including every output component. Leaves other types of dictionaries unchanged.
    E.g. {"textbox": "hello", "number": {"__type__": "generic_update", "value": "2"}}
    Into -> ["hello", {"__type__": "generic_update"}, {"__type__": "generic_update", "value": "2"}]
    """
    ...

def get_api_info(config: dict, serialize: bool = ...): # -> dict[str, dict[Any, Any]]:
    """
    Gets the information needed to generate the API docs from a Blocks config.
    Parameters:
        config: a Blocks config dictionary
        serialize: If True, returns the serialized version of the typed information. If False, returns the raw version.
    """
    ...

@document("launch", "queue", "integrate", "load")
class Blocks(BlockContext):
    """
    Blocks is Gradio's low-level API that allows you to create more custom web
    applications and demos than Interfaces (yet still entirely in Python).


    Compared to the Interface class, Blocks offers more flexibility and control over:
    (1) the layout of components (2) the events that
    trigger the execution of functions (3) data flows (e.g. inputs can trigger outputs,
    which can trigger the next level of outputs). Blocks also offers ways to group
    together related demos such as with tabs.


    The basic usage of Blocks is as follows: create a Blocks object, then use it as a
    context (with the "with" statement), and then define layouts, components, or events
    within the Blocks context. Finally, call the launch() method to launch the demo.

    Example:
        import gradio as gr
        def update(name):
            return f"Welcome to Gradio, {name}!"

        with gr.Blocks() as demo:
            gr.Markdown("Start typing below and then click **Run** to see the output.")
            with gr.Row():
                inp = gr.Textbox(placeholder="What is your name?")
                out = gr.Textbox()
            btn = gr.Button("Run")
            btn.click(fn=update, inputs=inp, outputs=out)

        demo.launch()
    Demos: blocks_hello, blocks_flipper, blocks_speech_text_sentiment, generate_english_german, sound_alert
    Guides: blocks-and-event-listeners, controlling-layout, state-in-blocks, custom-CSS-and-JS, custom-interpretations-with-blocks, using-blocks-like-functions
    """
    def __init__(self, theme: Theme | str | None = ..., analytics_enabled: bool | None = ..., mode: str = ..., title: str = ..., css: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            theme: a Theme object or a string representing a theme. If a string, will look for a built-in theme with that name (e.g. "soft" or "default"), or will attempt to load a theme from the HF Hub (e.g. "gradio/monochrome"). If None, will use the Default theme.
            analytics_enabled: whether to allow basic telemetry. If None, will use GRADIO_ANALYTICS_ENABLED environment variable or default to True.
            mode: a human-friendly name for the kind of Blocks or Interface being created.
            title: The tab title to display when this is opened in a browser window.
            css: custom css or path to custom css file to apply to entire Blocks
        """
        ...
    
    @classmethod
    def from_config(cls, config: dict, fns: list[Callable], root_url: str) -> Blocks:
        """
        Factory method that creates a Blocks from a config and list of functions. Used
        internally by the gradio.external.load() method.

        Parameters:
        config: a dictionary containing the configuration of the Blocks.
        fns: a list of functions that are used in the Blocks. Must be in the same order as the dependencies in the config.
        root_url: an external url to use as a root URL when serving files for components in the Blocks.
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def expects_oauth(self): # -> bool:
        """Return whether the app expects user to authenticate via OAuth."""
        ...
    
    def render(self): # -> Self:
        ...
    
    def is_callable(self, fn_index: int = ...) -> bool:
        """Checks if a particular Blocks function is callable (i.e. not stateful or a generator)."""
        ...
    
    def __call__(self, *inputs, fn_index: int = ..., api_name: str | None = ...): # -> Any:
        """
        Allows Blocks objects to be called as functions. Supply the parameters to the
        function as positional arguments. To choose which function to call, use the
        fn_index parameter, which must be a keyword argument.

        Parameters:
        *inputs: the parameters to pass to the function
        fn_index: the index of the function to call (defaults to 0, which for Interfaces, is the default prediction function)
        api_name: The api_name of the dependency to call. Will take precedence over fn_index.
        """
        ...
    
    async def call_function(self, fn_index: int, processed_input: list[Any], iterator: AsyncIterator[Any] | None = ..., requests: routes.Request | list[routes.Request] | None = ..., event_id: str | None = ..., event_data: EventData | None = ...): # -> dict[str, Any]:
        """
        Calls function with given index and preprocessed input, and measures process time.
        Parameters:
            fn_index: index of function to call
            processed_input: preprocessed input to pass to function
            iterator: iterator to use if function is a generator
            requests: requests to pass to function
            event_id: id of event in queue
            event_data: data associated with event trigger
        """
        ...
    
    def serialize_data(self, fn_index: int, inputs: list[Any]) -> list[Any]:
        ...
    
    def deserialize_data(self, fn_index: int, outputs: list[Any]) -> list[Any]:
        ...
    
    def validate_inputs(self, fn_index: int, inputs: list[Any]): # -> None:
        ...
    
    def preprocess_data(self, fn_index: int, inputs: list[Any], state: dict[int, Any]): # -> list[Any]:
        ...
    
    def validate_outputs(self, fn_index: int, predictions: Any | list[Any]): # -> None:
        ...
    
    def postprocess_data(self, fn_index: int, predictions: list | dict, state: dict[int, Any]): # -> list[Any]:
        ...
    
    def handle_streaming_outputs(self, fn_index: int, data: list, session_hash: str | None, run: int | None) -> list:
        ...
    
    async def process_api(self, fn_index: int, inputs: list[Any], state: dict[int, Any], request: routes.Request | list[routes.Request] | None = ..., iterators: dict[int, Any] | None = ..., session_hash: str | None = ..., event_id: str | None = ..., event_data: EventData | None = ...) -> dict[str, Any]:
        """
        Processes API calls from the frontend. First preprocesses the data,
        then runs the relevant function, then postprocesses the output.
        Parameters:
            fn_index: Index of function to run.
            inputs: input data received from the frontend
            state: data stored from stateful components for session (key is input block id)
            request: the gr.Request object containing information about the network request (e.g. IP address, headers, query parameters, username)
            iterators: the in-progress iterators for each generator function (key is function index)
            event_id: id of event that triggered this API call
            event_data: data associated with the event trigger itself
        Returns: None
        """
        ...
    
    async def create_limiter(self): # -> None:
        ...
    
    def get_config(self): # -> dict[str, str]:
        ...
    
    def get_config_file(self): # -> dict[str, Any]:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None = ..., *args): # -> None:
        ...
    
    def load(self: Blocks | None = ..., fn: Callable | None = ..., inputs: list[Component] | None = ..., outputs: list[Component] | None = ..., api_name: str | None | Literal[False] = ..., scroll_to_output: bool = ..., show_progress: str = ..., queue=..., batch: bool = ..., max_batch_size: int = ..., preprocess: bool = ..., postprocess: bool = ..., every: float | None = ..., _js: str | None = ..., *, name: str | None = ..., src: str | None = ..., api_key: str | None = ..., alias: str | None = ..., **kwargs) -> Blocks | dict[str, Any] | None:
        """
        For reverse compatibility reasons, this is both a class method and an instance
        method, the two of which, confusingly, do two completely different things.

        Class method: loads a demo from a Hugging Face Spaces repo and creates it locally and returns a block instance. Warning: this method will be deprecated. Use the equivalent `gradio.load()` instead.

        Instance method: adds event that runs as soon as the demo loads in the browser. Example usage below.
        Parameters:
            name: Class Method - the name of the model (e.g. "gpt2" or "facebook/bart-base") or space (e.g. "flax-community/spanish-gpt2"), can include the `src` as prefix (e.g. "models/facebook/bart-base")
            src: Class Method - the source of the model: `models` or `spaces` (or leave empty if source is provided as a prefix in `name`)
            api_key: Class Method - optional access token for loading private Hugging Face Hub models or spaces. Find your token here: https://huggingface.co/settings/tokens. Warning: only provide this if you are loading a trusted private Space as it can be read by the Space you are loading.
            alias: Class Method - optional string used as the name of the loaded model instead of the default name (only applies if loading a Space running Gradio 2.x)
            fn: Instance Method - the function to wrap an interface around. Often a machine learning model's prediction function. Each parameter of the function corresponds to one input component, and the function should return a single value or a tuple of values, with each element in the tuple corresponding to one output component.
            inputs: Instance Method - List of gradio.components to use as inputs. If the function takes no inputs, this should be an empty list.
            outputs: Instance Method - List of gradio.components to use as inputs. If the function returns no outputs, this should be an empty list.
            api_name: Instance Method - Defines how the endpoint appears in the API docs. Can be a string, None, or False. If False, the endpoint will not be exposed in the api docs. If set to None, the endpoint will be exposed in the api docs as an unnamed endpoint, although this behavior will be changed in Gradio 4.0. If set to a string, the endpoint will be exposed in the api docs with the given name.
            scroll_to_output: Instance Method - If True, will scroll to output component on completion
            show_progress: Instance Method - If True, will show progress animation while pending
            queue: Instance Method - If True, will place the request on the queue, if the queue exists
            batch: Instance Method - If True, then the function should process a batch of inputs, meaning that it should accept a list of input values for each parameter. The lists should be of equal length (and be up to length `max_batch_size`). The function is then *required* to return a tuple of lists (even if there is only 1 output component), with each list in the tuple corresponding to one output component.
            max_batch_size: Instance Method - Maximum number of inputs to batch together if this is called from the queue (only relevant if batch=True)
            preprocess: Instance Method - If False, will not run preprocessing of component data before running 'fn' (e.g. leaving it as a base64 string if this method is called with the `Image` component).
            postprocess: Instance Method - If False, will not run postprocessing of component data before returning 'fn' output to the browser.
            every: Instance Method - Run this event 'every' number of seconds. Interpreted in seconds. Queue must be enabled.
        Example:
            import gradio as gr
            import datetime
            with gr.Blocks() as demo:
                def get_time():
                    return datetime.datetime.now().time()
                dt = gr.Textbox(label="Current time")
                demo.load(get_time, inputs=None, outputs=dt)
            demo.launch()
        """
        ...
    
    def clear(self): # -> Self:
        """Resets the layout of the Blocks object."""
        ...
    
    @concurrency_count_warning
    @document()
    def queue(self, concurrency_count: int = ..., status_update_rate: float | Literal["auto"] = ..., client_position_to_load_data: int | None = ..., default_enabled: bool | None = ..., api_open: bool = ..., max_size: int | None = ...): # -> Self:
        """
        By enabling the queue you can control the rate of processed requests, let users know their position in the queue, and set a limit on maximum number of events allowed.
        Parameters:
            concurrency_count: Number of worker threads that will be processing requests from the queue concurrently. Increasing this number will increase the rate at which requests are processed, but will also increase the memory usage of the queue.
            status_update_rate: If "auto", Queue will send status estimations to all clients whenever a job is finished. Otherwise Queue will send status at regular intervals set by this parameter as the number of seconds.
            client_position_to_load_data: DEPRECATED. This parameter is deprecated and has no effect.
            default_enabled: Deprecated and has no effect.
            api_open: If True, the REST routes of the backend will be open, allowing requests made directly to those endpoints to skip the queue.
            max_size: The maximum number of events the queue will store at any given moment. If the queue is full, new events will not be added and a user will receive a message saying that the queue is full. If None, the queue size will be unlimited.
        Example: (Blocks)
            with gr.Blocks() as demo:
                button = gr.Button(label="Generate Image")
                button.click(fn=image_generator, inputs=gr.Textbox(), outputs=gr.Image())
            demo.queue(max_size=10)
            demo.launch()
        Example: (Interface)
            demo = gr.Interface(image_generator, gr.Textbox(), gr.Image())
            demo.queue(max_size=20)
            demo.launch()
        """
        ...
    
    def validate_queue_settings(self): # -> None:
        ...
    
    def launch(self, inline: bool | None = ..., inbrowser: bool = ..., share: bool | None = ..., debug: bool = ..., enable_queue: bool | None = ..., max_threads: int = ..., auth: Callable | tuple[str, str] | list[tuple[str, str]] | None = ..., auth_message: str | None = ..., prevent_thread_lock: bool = ..., show_error: bool = ..., server_name: str | None = ..., server_port: int | None = ..., show_tips: bool = ..., height: int = ..., width: int | str = ..., encrypt: bool | None = ..., favicon_path: str | None = ..., ssl_keyfile: str | None = ..., ssl_certfile: str | None = ..., ssl_keyfile_password: str | None = ..., ssl_verify: bool = ..., quiet: bool = ..., show_api: bool = ..., file_directories: list[str] | None = ..., allowed_paths: list[str] | None = ..., blocked_paths: list[str] | None = ..., root_path: str | None = ..., _frontend: bool = ..., app_kwargs: dict[str, Any] | None = ...) -> tuple[FastAPI, str, str]:
        """
        Launches a simple web server that serves the demo. Can also be used to create a
        public link used by anyone to access the demo from their browser by setting share=True.

        Parameters:
            inline: whether to display in the interface inline in an iframe. Defaults to True in python notebooks; False otherwise.
            inbrowser: whether to automatically launch the interface in a new tab on the default browser.
            share: whether to create a publicly shareable link for the interface. Creates an SSH tunnel to make your UI accessible from anywhere. If not provided, it is set to False by default every time, except when running in Google Colab. When localhost is not accessible (e.g. Google Colab), setting share=False is not supported.
            debug: if True, blocks the main thread from running. If running in Google Colab, this is needed to print the errors in the cell output.
            auth: If provided, username and password (or list of username-password tuples) required to access interface. Can also provide function that takes username and password and returns True if valid login.
            auth_message: If provided, HTML message provided on login page.
            prevent_thread_lock: If True, the interface will block the main thread while the server is running.
            show_error: If True, any errors in the interface will be displayed in an alert modal and printed in the browser console log
            server_port: will start gradio app on this port (if available). Can be set by environment variable GRADIO_SERVER_PORT. If None, will search for an available port starting at 7860.
            server_name: to make app accessible on local network, set this to "0.0.0.0". Can be set by environment variable GRADIO_SERVER_NAME. If None, will use "127.0.0.1".
            show_tips: if True, will occasionally show tips about new Gradio features
            enable_queue: DEPRECATED (use .queue() method instead.) if True, inference requests will be served through a queue instead of with parallel threads. Required for longer inference times (> 1min) to prevent timeout. The default option in HuggingFace Spaces is True. The default option elsewhere is False.
            max_threads: the maximum number of total threads that the Gradio app can generate in parallel. The default is inherited from the starlette library (currently 40). Applies whether the queue is enabled or not. But if queuing is enabled, this parameter is increaseed to be at least the concurrency_count of the queue.
            width: The width in pixels of the iframe element containing the interface (used if inline=True)
            height: The height in pixels of the iframe element containing the interface (used if inline=True)
            encrypt: DEPRECATED. Has no effect.
            favicon_path: If a path to a file (.png, .gif, or .ico) is provided, it will be used as the favicon for the web page.
            ssl_keyfile: If a path to a file is provided, will use this as the private key file to create a local server running on https.
            ssl_certfile: If a path to a file is provided, will use this as the signed certificate for https. Needs to be provided if ssl_keyfile is provided.
            ssl_keyfile_password: If a password is provided, will use this with the ssl certificate for https.
            ssl_verify: If False, skips certificate validation which allows self-signed certificates to be used.
            quiet: If True, suppresses most print statements.
            show_api: If True, shows the api docs in the footer of the app. Default True. If the queue is enabled, then api_open parameter of .queue() will determine if the api docs are shown, independent of the value of show_api.
            file_directories: This parameter has been renamed to `allowed_paths`. It will be removed in a future version.
            allowed_paths: List of complete filepaths or parent directories that gradio is allowed to serve (in addition to the directory containing the gradio python file). Must be absolute paths. Warning: if you provide directories, any files in these directories or their subdirectories are accessible to all users of your app.
            blocked_paths: List of complete filepaths or parent directories that gradio is not allowed to serve (i.e. users of your app are not allowed to access). Must be absolute paths. Warning: takes precedence over `allowed_paths` and all other directories exposed by Gradio by default.
            root_path: The root path (or "mount point") of the application, if it's not served from the root ("/") of the domain. Often used when the application is behind a reverse proxy that forwards requests to the application. For example, if the application is served at "https://example.com/myapp", the `root_path` should be set to "/myapp". Can be set by environment variable GRADIO_ROOT_PATH. Defaults to "".
            app_kwargs: Additional keyword arguments to pass to the underlying FastAPI app as a dictionary of parameter keys and argument values. For example, `{"docs_url": "/docs"}`
        Returns:
            app: FastAPI app object that is running the demo
            local_url: Locally accessible link to the demo
            share_url: Publicly accessible link to the demo (if share=True, otherwise None)
        Example: (Blocks)
            import gradio as gr
            def reverse(text):
                return text[::-1]
            with gr.Blocks() as demo:
                button = gr.Button(value="Reverse")
                button.click(reverse, gr.Textbox(), gr.Textbox())
            demo.launch(share=True, auth=("username", "password"))
        Example:  (Interface)
            import gradio as gr
            def reverse(text):
                return text[::-1]
            demo = gr.Interface(reverse, "text", "text")
            demo.launch(share=True, auth=("username", "password"))
        """
        ...
    
    def integrate(self, comet_ml=..., wandb: ModuleType | None = ..., mlflow: ModuleType | None = ...) -> None:
        """
        A catch-all method for integrating with other libraries. This method should be run after launch()
        Parameters:
            comet_ml: If a comet_ml Experiment object is provided, will integrate with the experiment and appear on Comet dashboard
            wandb: If the wandb module is provided, will integrate with it and appear on WandB dashboard
            mlflow: If the mlflow module  is provided, will integrate with the experiment and appear on ML Flow dashboard
        """
        ...
    
    def close(self, verbose: bool = ...) -> None:
        """
        Closes the Interface that was launched and frees the port.
        """
        ...
    
    def block_thread(self) -> None:
        """Block main thread until interrupted by user."""
        ...
    
    def attach_load_events(self): # -> None:
        """Add a load event for every component whose initial value should be randomized."""
        ...
    
    def startup_events(self): # -> None:
        """Events that should be run when the app containing this block starts up."""
        ...
    
    def queue_enabled_for_fn(self, fn_index: int): # -> bool | None:
        ...
    


