"""
This type stub file was generated by pyright.
"""

class GradioDeprecationWarning(UserWarning):
    ...


class GradioUnusedKwargWarning(UserWarning):
    ...


def simple_deprecated_notice(term: str) -> str:
    ...

def use_in_launch(term: str) -> str:
    ...

DEPRECATION_MESSAGE = ...
def check_deprecated_parameters(cls: str, *, stacklevel: int | None = ..., kwargs) -> None:
    ...

def warn_deprecation(text: str) -> None:
    ...

def warn_style_method_deprecation() -> None:
    ...

