"""
This type stub file was generated by pyright.
"""

from gradio_client.documentation import document

class DuplicateBlockError(ValueError):
    """Raised when a Blocks contains more than one Block with the same id"""
    ...


class TooManyRequestsError(Exception):
    """Raised when the Hugging Face API returns a 429 status code."""
    ...


class InvalidApiNameError(ValueError):
    ...


class ServerFailedToStartError(Exception):
    ...


class InvalidBlockError(ValueError):
    """Raised when an event in a Blocks contains a reference to a Block that is not in the original Blocks"""
    ...


InvalidApiName = InvalidApiNameError
@document()
class Error(Exception):
    """
    This class allows you to pass custom error messages to the user. You can do so by raising a gr.Error("custom message") anywhere in the code, and when that line is executed the custom message will appear in a modal on the demo.

    Demos: calculator
    """
    def __init__(self, message: str = ...) -> None:
        """
        Parameters:
            message: The error message to be displayed to the user.
        """
        ...
    
    def __str__(self) -> str:
        ...
    


