"""
This type stub file was generated by pyright.
"""

import requests
from typing import Dict, List, Tuple

"""Utility function for gradio/external.py"""
def get_tabular_examples(model_name: str) -> Dict[str, List[float]]:
    ...

def cols_to_rows(example_data: Dict[str, List[float]]) -> Tuple[List[str], List[List[float]]]:
    ...

def rows_to_cols(incoming_data: Dict) -> Dict[str, Dict[str, Dict[str, List[str]]]]:
    ...

def postprocess_label(scores: Dict) -> Dict:
    ...

def encode_to_base64(r: requests.Response) -> str:
    ...

def streamline_spaces_interface(config: Dict) -> Dict:
    """Streamlines the interface config dictionary to remove unnecessary keys."""
    ...

