"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from gradio_client.documentation import document
from gradio.blocks import Blocks
from gradio.interface import Interface

"""This module should not be used directly as its API is subject to change. Instead,
use the `gr.Blocks.load()` or `gr.load()` functions."""
if TYPE_CHECKING:
    ...
@document()
def load(name: str, src: str | None = ..., api_key: str | None = ..., hf_token: str | None = ..., alias: str | None = ..., **kwargs) -> Blocks:
    """
    Method that constructs a Blocks from a Hugging Face repo. Can accept
    model repos (if src is "models") or Space repos (if src is "spaces"). The input
    and output components are automatically loaded from the repo.
    Parameters:
        name: the name of the model (e.g. "gpt2" or "facebook/bart-base") or space (e.g. "flax-community/spanish-gpt2"), can include the `src` as prefix (e.g. "models/facebook/bart-base")
        src: the source of the model: `models` or `spaces` (or leave empty if source is provided as a prefix in `name`)
        api_key: Deprecated. Please use the `hf_token` parameter instead.
        hf_token: optional access token for loading private Hugging Face Hub models or spaces. Find your token here: https://huggingface.co/settings/tokens.  Warning: only provide this if you are loading a trusted private Space as it can be read by the Space you are loading.
        alias: optional string used as the name of the loaded model instead of the default name (only applies if loading a Space running Gradio 2.x)
    Returns:
        a Gradio Blocks object for the given model
    Example:
        import gradio as gr
        demo = gr.load("gradio/question-answering", src="spaces")
        demo.launch()
    """
    ...

def load_blocks_from_repo(name: str, src: str | None = ..., hf_token: str | None = ..., alias: str | None = ..., **kwargs) -> Blocks:
    """Creates and returns a Blocks instance from a Hugging Face model or Space repo."""
    ...

def chatbot_preprocess(text, state): # -> dict[str, dict[str, Any]]:
    ...

def chatbot_postprocess(response): # -> tuple[list[tuple[Any, Any]], Any]:
    ...

def from_model(model_name: str, hf_token: str | None, alias: str | None, **kwargs): # -> Interface:
    ...

def from_spaces(space_name: str, hf_token: str | None, alias: str | None, **kwargs) -> Blocks:
    ...

def from_spaces_blocks(space: str, hf_token: str | None) -> Blocks:
    ...

def from_spaces_interface(model_name: str, config: dict, alias: str | None, hf_token: str | None, iframe_url: str, **kwargs) -> Interface:
    ...

