"""
This type stub file was generated by pyright.
"""

import gradio as gr
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, TYPE_CHECKING
from gradio_client.documentation import document
from gradio.components import IOComponent

if TYPE_CHECKING:
    ...
class FlaggingCallback(ABC):
    """
    An abstract class for defining the methods that any FlaggingCallback should have.
    """
    @abstractmethod
    def setup(self, components: list[IOComponent], flagging_dir: str): # -> None:
        """
        This method should be overridden and ensure that everything is set up correctly for flag().
        This method gets called once at the beginning of the Interface.launch() method.
        Parameters:
        components: Set of components that will provide flagged data.
        flagging_dir: A string, typically containing the path to the directory where the flagging file should be storied (provided as an argument to Interface.__init__()).
        """
        ...
    
    @abstractmethod
    def flag(self, flag_data: list[Any], flag_option: str = ..., username: str | None = ...) -> int:
        """
        This method should be overridden by the FlaggingCallback subclass and may contain optional additional arguments.
        This gets called every time the <flag> button is pressed.
        Parameters:
        interface: The Interface object that is being used to launch the flagging interface.
        flag_data: The data to be flagged.
        flag_option (optional): In the case that flagging_options are provided, the flag option that is being used.
        username (optional): The username of the user that is flagging the data, if logged in.
        Returns:
        (int) The total number of samples that have been flagged.
        """
        ...
    


@document()
class SimpleCSVLogger(FlaggingCallback):
    """
    A simplified implementation of the FlaggingCallback abstract class
    provided for illustrative purposes.  Each flagged sample (both the input and output data)
    is logged to a CSV file on the machine running the gradio app.
    Example:
        import gradio as gr
        def image_classifier(inp):
            return {'cat': 0.3, 'dog': 0.7}
        demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label",
                            flagging_callback=SimpleCSVLogger())
    """
    def __init__(self) -> None:
        ...
    
    def setup(self, components: list[IOComponent], flagging_dir: str | Path): # -> None:
        ...
    
    def flag(self, flag_data: list[Any], flag_option: str = ..., username: str | None = ...) -> int:
        ...
    


@document()
class CSVLogger(FlaggingCallback):
    """
    The default implementation of the FlaggingCallback abstract class. Each flagged
    sample (both the input and output data) is logged to a CSV file with headers on the machine running the gradio app.
    Example:
        import gradio as gr
        def image_classifier(inp):
            return {'cat': 0.3, 'dog': 0.7}
        demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label",
                            flagging_callback=CSVLogger())
    Guides: using-flagging
    """
    def __init__(self) -> None:
        ...
    
    def setup(self, components: list[IOComponent], flagging_dir: str | Path): # -> None:
        ...
    
    def flag(self, flag_data: list[Any], flag_option: str = ..., username: str | None = ...) -> int:
        ...
    


@document()
class HuggingFaceDatasetSaver(FlaggingCallback):
    """
    A callback that saves each flagged sample (both the input and output data) to a HuggingFace dataset.

    Example:
        import gradio as gr
        hf_writer = gr.HuggingFaceDatasetSaver(HF_API_TOKEN, "image-classification-mistakes")
        def image_classifier(inp):
            return {'cat': 0.3, 'dog': 0.7}
        demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label",
                            allow_flagging="manual", flagging_callback=hf_writer)
    Guides: using-flagging
    """
    def __init__(self, hf_token: str, dataset_name: str, organization: str | None = ..., private: bool = ..., info_filename: str = ..., separate_dirs: bool = ..., verbose: bool = ...) -> None:
        """
        Parameters:
            hf_token: The HuggingFace token to use to create (and write the flagged sample to) the HuggingFace dataset (defaults to the registered one).
            dataset_name: The repo_id of the dataset to save the data to, e.g. "image-classifier-1" or "username/image-classifier-1".
            organization: Deprecated argument. Please pass a full dataset id (e.g. 'username/dataset_name') to `dataset_name` instead.
            private: Whether the dataset should be private (defaults to False).
            info_filename: The name of the file to save the dataset info (defaults to "dataset_infos.json").
            separate_dirs: If True, each flagged item will be saved in a separate directory. This makes the flagging more robust to concurrent editing, but may be less convenient to use.
        """
        ...
    
    def setup(self, components: list[IOComponent], flagging_dir: str): # -> None:
        """
        Params:
        flagging_dir (str): local directory where the dataset is cloned,
        updated, and pushed from.
        """
        ...
    
    def flag(self, flag_data: list[Any], flag_option: str = ..., username: str | None = ...) -> int:
        ...
    


class HuggingFaceDatasetJSONSaver(HuggingFaceDatasetSaver):
    def __init__(self, hf_token: str, dataset_name: str, organization: str | None = ..., private: bool = ..., info_filename: str = ..., verbose: bool = ...) -> None:
        ...
    


class FlagMethod:
    """
    Helper class that contains the flagging options and calls the flagging method. Also
    provides visual feedback to the user when flag is clicked.
    """
    def __init__(self, flagging_callback: FlaggingCallback, label: str, value: str, visual_feedback: bool = ...) -> None:
        ...
    
    def __call__(self, request: gr.Request, *flag_data): # -> dict[str, Any] | Literal['Error!'] | None:
        ...
    
    def reset(self): # -> dict[str, Any]:
        ...
    


