"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Any, Callable, Iterable, Literal, TYPE_CHECKING
from gradio_client.documentation import document
from gradio import routes
from gradio.blocks import Block
from gradio.components import IOComponent

"""
Defines helper methods useful for loading and caching Interface examples.
"""
if TYPE_CHECKING:
    ...
CACHED_FOLDER = ...
LOG_FILE = ...
def create_examples(examples: list[Any] | list[list[Any]] | str, inputs: IOComponent | list[IOComponent], outputs: IOComponent | list[IOComponent] | None = ..., fn: Callable | None = ..., cache_examples: bool = ..., examples_per_page: int = ..., _api_mode: bool = ..., label: str | None = ..., elem_id: str | None = ..., run_on_click: bool = ..., preprocess: bool = ..., postprocess: bool = ..., api_name: str | None | Literal[False] = ..., batch: bool = ...): # -> Examples:
    """Top-level synchronous function that creates Examples. Provided for backwards compatibility, i.e. so that gr.Examples(...) can be used to create the Examples component."""
    ...

@document()
class Examples:
    """
    This class is a wrapper over the Dataset component and can be used to create Examples
    for Blocks / Interfaces. Populates the Dataset component with examples and
    assigns event listener so that clicking on an example populates the input/output
    components. Optionally handles example caching for fast inference.

    Demos: blocks_inputs, fake_gan
    Guides: more-on-examples-and-flagging, using-hugging-face-integrations, image-classification-in-pytorch, image-classification-in-tensorflow, image-classification-with-vision-transformers, create-your-own-friends-with-a-gan
    """
    def __init__(self, examples: list[Any] | list[list[Any]] | str, inputs: IOComponent | list[IOComponent], outputs: IOComponent | list[IOComponent] | None = ..., fn: Callable | None = ..., cache_examples: bool = ..., examples_per_page: int = ..., _api_mode: bool = ..., label: str | None = ..., elem_id: str | None = ..., run_on_click: bool = ..., preprocess: bool = ..., postprocess: bool = ..., api_name: str | None | Literal[False] = ..., batch: bool = ..., _initiated_directly: bool = ...) -> None:
        """
        Parameters:
            examples: example inputs that can be clicked to populate specific components. Should be nested list, in which the outer list consists of samples and each inner list consists of an input corresponding to each input component. A string path to a directory of examples can also be provided but it should be within the directory with the python file running the gradio app. If there are multiple input components and a directory is provided, a log.csv file must be present in the directory to link corresponding inputs.
            inputs: the component or list of components corresponding to the examples
            outputs: optionally, provide the component or list of components corresponding to the output of the examples. Required if `cache` is True.
            fn: optionally, provide the function to run to generate the outputs corresponding to the examples. Required if `cache` is True.
            cache_examples: if True, caches examples for fast runtime. If True, then `fn` and `outputs` must be provided. If `fn` is a generator function, then the last yielded value will be used as the output.
            examples_per_page: how many examples to show per page.
            label: the label to use for the examples component (by default, "Examples")
            elem_id: an optional string that is assigned as the id of this component in the HTML DOM.
            run_on_click: if cache_examples is False, clicking on an example does not run the function when an example is clicked. Set this to True to run the function when an example is clicked. Has no effect if cache_examples is True.
            preprocess: if True, preprocesses the example input before running the prediction function and caching the output. Only applies if cache_examples is True.
            postprocess: if True, postprocesses the example output after running the prediction function and before caching. Only applies if cache_examples is True.
            api_name: Defines how the event associated with clicking on the examples appears in the API docs. Can be a string, None, or False. If False (default), the endpoint will not be exposed in the api docs. If set to None, the endpoint will be exposed in the api docs as an unnamed endpoint, although this behavior will be changed in Gradio 4.0. If set to a string, the endpoint will be exposed in the api docs with the given name.
            batch: If True, then the function should process a batch of inputs, meaning that it should accept a list of input values for each parameter. Used only if cache_examples is True.
        """
        ...
    
    async def create(self) -> None:
        """Caches the examples if self.cache_examples is True and creates the Dataset
        component to hold the examples"""
        ...
    
    async def cache(self) -> None:
        """
        Caches all of the examples so that their predictions can be shown immediately.
        """
        ...
    
    async def load_from_cache(self, example_id: int) -> list[Any]:
        """Loads a particular cached example for the interface.
        Parameters:
            example_id: The id of the example to process (zero-indexed).
        """
        ...
    


def merge_generated_values_into_output(components: list[IOComponent], generated_values: list, output: list): # -> list[Any]:
    ...

class TrackedIterable:
    def __init__(self, iterable: Iterable | None, index: int | None, length: int | None, desc: str | None, unit: str | None, _tqdm=..., progress: float | None = ...) -> None:
        ...
    


@document("__call__", "tqdm")
class Progress(Iterable):
    """
    The Progress class provides a custom progress tracker that is used in a function signature.
    To attach a Progress tracker to a function, simply add a parameter right after the input parameters that has a default value set to a `gradio.Progress()` instance.
    The Progress tracker can then be updated in the function by calling the Progress object or using the `tqdm` method on an Iterable.
    The Progress tracker is currently only available with `queue()`.
    Example:
        import gradio as gr
        import time
        def my_function(x, progress=gr.Progress()):
            progress(0, desc="Starting...")
            time.sleep(1)
            for i in progress.tqdm(range(100)):
                time.sleep(0.1)
            return x
        gr.Interface(my_function, gr.Textbox(), gr.Textbox()).queue().launch()
    Demos: progress
    """
    def __init__(self, track_tqdm: bool = ..., _callback: Callable | None = ..., _event_id: str | None = ...) -> None:
        """
        Parameters:
            track_tqdm: If True, the Progress object will track any tqdm.tqdm iterations with the tqdm library in the function.
        """
        ...
    
    def __len__(self): # -> int | None:
        ...
    
    def __iter__(self): # -> Self:
        ...
    
    def __next__(self): # -> Self:
        """
        Updates progress tracker with next item in iterable.
        """
        ...
    
    def __call__(self, progress: float | tuple[int, int | None] | None, desc: str | None = ..., total: int | None = ..., unit: str = ..., _tqdm=...): # -> float | tuple[int, int | None] | None:
        """
        Updates progress tracker with progress and message text.
        Parameters:
            progress: If float, should be between 0 and 1 representing completion. If Tuple, first number represents steps completed, and second value represents total steps or None if unknown. If None, hides progress bar.
            desc: description to display.
            total: estimated total number of steps.
            unit: unit of iterations.
        """
        ...
    
    def tqdm(self, iterable: Iterable | None, desc: str | None = ..., total: int | None = ..., unit: str = ..., _tqdm=...): # -> Self:
        """
        Attaches progress tracker to iterable, like tqdm.
        Parameters:
            iterable: iterable to attach progress tracker to.
            desc: description to display.
            total: estimated total number of steps.
            unit: unit of iterations.
        """
        ...
    
    def update(self, n=...): # -> None:
        """
        Increases latest iterable with specified number of steps.
        Parameters:
            n: number of steps completed.
        """
        ...
    
    def close(self, _tqdm): # -> None:
        """
        Removes iterable with given _tqdm.
        """
        ...
    


def create_tracker(root_blocks, event_id, fn, track_tqdm): # -> tuple[Progress, Any] | tuple[Progress, _Wrapped[Callable[..., Any], Any, Callable[..., Any], AsyncGenerator[Any, Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], CoroutineType[Any, Any, Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Generator[Any, Any, None]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
    ...

def special_args(fn: Callable, inputs: list[Any] | None = ..., request: routes.Request | None = ..., event_data: EventData | None = ...): # -> tuple[list[Any], int | None, int | None]:
    """
    Checks if function has special arguments Request or EventData (via annotation) or Progress (via default value).
    If inputs is provided, these values will be loaded into the inputs array.
    Parameters:
        fn: function to check.
        inputs: array to load special arguments into.
        request: request to load into inputs.
        event_data: event-related data to load into inputs.
    Returns:
        updated inputs, progress index, event data index.
    """
    ...

@document()
def update(**kwargs) -> dict:
    """
    Updates component properties. When a function passed into a Gradio Interface or a Blocks events returns a typical value, it updates the value of the output component. But it is also possible to update the properties of an output component (such as the number of lines of a `Textbox` or the visibility of an `Image`) by returning the component's `update()` function, which takes as parameters any of the constructor parameters for that component.
    This is a shorthand for using the update method on a component.
    For example, rather than using gr.Number.update(...) you can just use gr.update(...).
    Note that your editor's autocompletion will suggest proper parameters
    if you use the update method on the component.
    Demos: blocks_essay, blocks_update, blocks_essay_update

    Parameters:
        kwargs: Key-word arguments used to update the component's properties.
    Example:
        # Blocks Example
        import gradio as gr
        with gr.Blocks() as demo:
            radio = gr.Radio([1, 2, 4], label="Set the value of the number")
            number = gr.Number(value=2, interactive=True)
            radio.change(fn=lambda value: gr.update(value=value), inputs=radio, outputs=number)
        demo.launch()

        # Interface example
        import gradio as gr
        def change_textbox(choice):
          if choice == "short":
              return gr.Textbox.update(lines=2, visible=True)
          elif choice == "long":
              return gr.Textbox.update(lines=8, visible=True)
          else:
              return gr.Textbox.update(visible=False)
        gr.Interface(
          change_textbox,
          gr.Radio(
              ["short", "long", "none"], label="What kind of essay would you like to write?"
          ),
          gr.Textbox(lines=2),
          live=True,
        ).launch()
    """
    ...

def skip() -> dict:
    ...

@document()
def make_waveform(audio: str | tuple[int, np.ndarray], *, bg_color: str = ..., bg_image: str | None = ..., fg_alpha: float = ..., bars_color: str | tuple[str, str] = ..., bar_count: int = ..., bar_width: float = ..., animate: bool = ...) -> str:
    """
    Generates a waveform video from an audio file. Useful for creating an easy to share audio visualization. The output should be passed into a `gr.Video` component.
    Parameters:
        audio: Audio file path or tuple of (sample_rate, audio_data)
        bg_color: Background color of waveform (ignored if bg_image is provided)
        bg_image: Background image of waveform
        fg_alpha: Opacity of foreground waveform
        bars_color: Color of waveform bars. Can be a single color or a tuple of (start_color, end_color) of gradient
        bar_count: Number of bars in waveform
        bar_width: Width of bars in waveform. 1 represents full width, 0.5 represents half width, etc.
        animate: If true, the audio waveform overlay will be animated, if false, it will be static.
    Returns:
        A filepath to the output video in mp4 format.
    """
    ...

@document()
class EventData:
    """
    When a subclass of EventData is added as a type hint to an argument of an event listener method, this object will be passed as that argument.
    It contains information about the event that triggered the listener, such the target object, and other data related to the specific event that are attributes of the subclass.

    Example:
        table = gr.Dataframe([[1, 2, 3], [4, 5, 6]])
        gallery = gr.Gallery([("cat.jpg", "Cat"), ("dog.jpg", "Dog")])
        textbox = gr.Textbox("Hello World!")

        statement = gr.Textbox()

        def on_select(evt: gr.SelectData):  # SelectData is a subclass of EventData
            return f"You selected {evt.value} at {evt.index} from {evt.target}"

        table.select(on_select, None, statement)
        gallery.select(on_select, None, statement)
        textbox.select(on_select, None, statement)
    Demos: gallery_selections, tictactoe
    """
    def __init__(self, target: Block | None, _data: Any) -> None:
        """
        Parameters:
            target: The target object that triggered the event. Can be used to distinguish if multiple components are bound to the same listener.
        """
        ...
    


def log_message(message: str, level: Literal["info", "warning"] = ...): # -> None:
    ...

@document()
def Warning(message: str = ...): # -> None:
    """
    This function allows you to pass custom warning messages to the user. You can do so simply with `gr.Warning('message here')`, and when that line is executed the custom message will appear in a modal on the demo.
    Parameters:
        message: The warning message to be displayed to the user.
    """
    ...

@document()
def Info(message: str = ...): # -> None:
    """
    Parameters:
        message: The info message to be displayed to the user.
    """
    ...

