"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, TYPE_CHECKING
from gradio import Interface

"""Contains classes and methods related to interpretation for components in Gradio."""
if TYPE_CHECKING:
    ...
class Interpretable(ABC):
    def __init__(self) -> None:
        ...
    
    def set_interpret_parameters(self): # -> None:
        """
        Set any parameters for interpretation. Properties can be set here to be
        used in get_interpretation_neighbors and get_interpretation_scores.
        """
        ...
    
    def get_interpretation_scores(self, x: Any, neighbors: list[Any] | None, scores: list[float], **kwargs) -> list:
        """
        Arrange the output values from the neighbors into interpretation scores for the interface to render.
        Parameters:
            x: Input to interface
            neighbors: Neighboring values to input x used for interpretation.
            scores: Output value corresponding to each neighbor in neighbors
        Returns:
            Arrangement of interpretation scores for interfaces to render.
        """
        ...
    


class TokenInterpretable(Interpretable, ABC):
    @abstractmethod
    def tokenize(self, x: Any) -> tuple[list, list, None]:
        """
        Interprets an input data point x by splitting it into a list of tokens (e.g
        a string into words or an image into super-pixels).
        """
        ...
    
    @abstractmethod
    def get_masked_inputs(self, tokens: list, binary_mask_matrix: list[list]) -> list:
        ...
    


class NeighborInterpretable(Interpretable, ABC):
    @abstractmethod
    def get_interpretation_neighbors(self, x: Any) -> tuple[list, dict]:
        """
        Generates values similar to input to be used to interpret the significance of the input in the final output.
        Parameters:
            x: Input to interface
        Returns: (neighbor_values, interpret_kwargs, interpret_by_removal)
            neighbor_values: Neighboring values to input x to compute for interpretation
            interpret_kwargs: Keyword arguments to be passed to get_interpretation_scores
        """
        ...
    


async def run_interpret(interface: Interface, raw_input: list): # -> tuple[list[Any], list[Any]] | tuple[list[Any] | Any, list[Any]]:
    """
    Runs the interpretation command for the machine learning model. Handles both the "default" out-of-the-box
    interpretation for a certain set of UI component types, as well as the custom interpretation case.
    Parameters:
    raw_input: a list of raw inputs to apply the interpretation(s) on.
    """
    ...

def diff(original: Any, perturbed: Any) -> int | float:
    ...

def quantify_difference_in_label(interface: Interface, original_output: list, perturbed_output: list) -> int | float:
    ...

def get_regression_or_classification_value(interface: Interface, original_output: list, perturbed_output: list) -> int | float:
    """Used to combine regression/classification for Shap interpretation method."""
    ...

