"""
This type stub file was generated by pyright.
"""

import weakref
from typing import Any, Callable, Literal, TYPE_CHECKING
from gradio_client.documentation import document
from gradio.blocks import Blocks
from gradio.components import Button, ClearButton, DuplicateButton, IOComponent, Interpretation
from gradio.flagging import FlaggingCallback
from gradio.layouts import Column
from gradio.themes import ThemeClass as Theme
from transformers.pipelines.base import Pipeline

"""
This file defines two useful high-level abstractions to build Gradio apps: Interface and TabbedInterface.
"""
if TYPE_CHECKING:
    ...
@document("launch", "load", "from_pipeline", "integrate", "queue")
class Interface(Blocks):
    """
    Interface is Gradio's main high-level class, and allows you to create a web-based GUI / demo
    around a machine learning model (or any Python function) in a few lines of code.
    You must specify three parameters: (1) the function to create a GUI for (2) the desired input components and
    (3) the desired output components. Additional parameters can be used to control the appearance
    and behavior of the demo.

    Example:
        import gradio as gr

        def image_classifier(inp):
            return {'cat': 0.3, 'dog': 0.7}

        demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label")
        demo.launch()
    Demos: hello_world, hello_world_3, gpt2_xl
    Guides: quickstart, key-features, sharing-your-app, interface-state, reactive-interfaces, advanced-interface-features, setting-up-a-gradio-demo-for-maximum-performance
    """
    instances: weakref.WeakSet = ...
    @classmethod
    def get_instances(cls) -> list[Interface]:
        """
        :return: list of all current instances.
        """
        ...
    
    @classmethod
    def load(cls, name: str, src: str | None = ..., api_key: str | None = ..., alias: str | None = ..., **kwargs) -> Blocks:
        """
        Warning: this method will be deprecated. Use the equivalent `gradio.load()` instead. This is a class
        method that constructs a Blocks from a Hugging Face repo. Can accept
        model repos (if src is "models") or Space repos (if src is "spaces"). The input
        and output components are automatically loaded from the repo.
        Parameters:
            name: the name of the model (e.g. "gpt2" or "facebook/bart-base") or space (e.g. "flax-community/spanish-gpt2"), can include the `src` as prefix (e.g. "models/facebook/bart-base")
            src: the source of the model: `models` or `spaces` (or leave empty if source is provided as a prefix in `name`)
            api_key: optional access token for loading private Hugging Face Hub models or spaces. Find your token here: https://huggingface.co/settings/tokens. Warning: only provide this if you are loading a trusted private Space as it can be read by the Space you are loading.
            alias: optional string used as the name of the loaded model instead of the default name (only applies if loading a Space running Gradio 2.x)
        Returns:
            a Gradio Interface object for the given model
        """
        ...
    
    @classmethod
    def from_pipeline(cls, pipeline: Pipeline, **kwargs) -> Interface:
        """
        Class method that constructs an Interface from a Hugging Face transformers.Pipeline object.
        The input and output components are automatically determined from the pipeline.
        Parameters:
            pipeline: the pipeline object to use.
        Returns:
            a Gradio Interface object from the given Pipeline
        Example:
            import gradio as gr
            from transformers import pipeline
            pipe = pipeline("image-classification")
            gr.Interface.from_pipeline(pipe).launch()
        """
        ...
    
    def __init__(self, fn: Callable, inputs: str | IOComponent | list[str | IOComponent] | None, outputs: str | IOComponent | list[str | IOComponent] | None, examples: list[Any] | list[list[Any]] | str | None = ..., cache_examples: bool | None = ..., examples_per_page: int = ..., live: bool = ..., interpretation: Callable | str | None = ..., num_shap: float = ..., title: str | None = ..., description: str | None = ..., article: str | None = ..., thumbnail: str | None = ..., theme: Theme | str | None = ..., css: str | None = ..., allow_flagging: str | None = ..., flagging_options: list[str] | list[tuple[str, str]] | None = ..., flagging_dir: str = ..., flagging_callback: FlaggingCallback = ..., analytics_enabled: bool | None = ..., batch: bool = ..., max_batch_size: int = ..., api_name: str | Literal[False] | None = ..., _api_mode: bool = ..., allow_duplication: bool = ..., **kwargs) -> None:
        """
        Parameters:
            fn: the function to wrap an interface around. Often a machine learning model's prediction function. Each parameter of the function corresponds to one input component, and the function should return a single value or a tuple of values, with each element in the tuple corresponding to one output component.
            inputs: a single Gradio component, or list of Gradio components. Components can either be passed as instantiated objects, or referred to by their string shortcuts. The number of input components should match the number of parameters in fn. If set to None, then only the output components will be displayed.
            outputs: a single Gradio component, or list of Gradio components. Components can either be passed as instantiated objects, or referred to by their string shortcuts. The number of output components should match the number of values returned by fn. If set to None, then only the input components will be displayed.
            examples: sample inputs for the function; if provided, appear below the UI components and can be clicked to populate the interface. Should be nested list, in which the outer list consists of samples and each inner list consists of an input corresponding to each input component. A string path to a directory of examples can also be provided, but it should be within the directory with the python file running the gradio app. If there are multiple input components and a directory is provided, a log.csv file must be present in the directory to link corresponding inputs.
            cache_examples: If True, caches examples in the server for fast runtime in examples. If `fn` is a generator function, then the last yielded value will be used as the output. The default option in HuggingFace Spaces is True. The default option elsewhere is False.
            examples_per_page: If examples are provided, how many to display per page.
            live: whether the interface should automatically rerun if any of the inputs change.
            interpretation: function that provides interpretation explaining prediction output. Pass "default" to use simple built-in interpreter, "shap" to use a built-in shapley-based interpreter, or your own custom interpretation function. For more information on the different interpretation methods, see the Advanced Interface Features guide.
            num_shap: a multiplier that determines how many examples are computed for shap-based interpretation. Increasing this value will increase shap runtime, but improve results. Only applies if interpretation is "shap".
            title: a title for the interface; if provided, appears above the input and output components in large font. Also used as the tab title when opened in a browser window.
            description: a description for the interface; if provided, appears above the input and output components and beneath the title in regular font. Accepts Markdown and HTML content.
            article: an expanded article explaining the interface; if provided, appears below the input and output components in regular font. Accepts Markdown and HTML content.
            thumbnail: path or url to image to use as display image when the web demo is shared on social media.
            theme: Theme to use, loaded from gradio.themes.
            css: custom css or path to custom css file to use with interface.
            allow_flagging: one of "never", "auto", or "manual". If "never" or "auto", users will not see a button to flag an input and output. If "manual", users will see a button to flag. If "auto", every input the user submits will be automatically flagged (outputs are not flagged). If "manual", both the input and outputs are flagged when the user clicks flag button. This parameter can be set with environmental variable GRADIO_ALLOW_FLAGGING; otherwise defaults to "manual".
            flagging_options: if provided, allows user to select from the list of options when flagging. Only applies if allow_flagging is "manual". Can either be a list of tuples of the form (label, value), where label is the string that will be displayed on the button and value is the string that will be stored in the flagging CSV; or it can be a list of strings ["X", "Y"], in which case the values will be the list of strings and the labels will ["Flag as X", "Flag as Y"], etc.
            flagging_dir: what to name the directory where flagged data is stored.
            flagging_callback: An instance of a subclass of FlaggingCallback which will be called when a sample is flagged. By default logs to a local CSV file.
            analytics_enabled: Whether to allow basic telemetry. If None, will use GRADIO_ANALYTICS_ENABLED environment variable if defined, or default to True.
            batch: If True, then the function should process a batch of inputs, meaning that it should accept a list of input values for each parameter. The lists should be of equal length (and be up to length `max_batch_size`). The function is then *required* to return a tuple of lists (even if there is only 1 output component), with each list in the tuple corresponding to one output component.
            max_batch_size: Maximum number of inputs to batch together if this is called from the queue (only relevant if batch=True)
            api_name: Defines how the endpoint appears in the API docs. Can be a string, None, or False. If False or None, the endpoint will not be exposed in the api docs. If set to a string, the endpoint will be exposed in the api docs with the given name. Default value is "predict".
            allow_duplication: If True, then will show a 'Duplicate Spaces' button on Hugging Face Spaces.
        """
        ...
    
    def render_title_description(self) -> None:
        ...
    
    def render_flag_btns(self) -> list[Button]:
        ...
    
    def render_input_column(self) -> tuple[Button | None, ClearButton | None, Button | None, list[Button] | None, Column, Column | None, list[Interpretation] | None,]:
        ...
    
    def render_output_column(self, submit_btn_in: Button | None) -> tuple[Button | None, ClearButton | None, DuplicateButton, Button | None, list | None, Button | None,]:
        ...
    
    def render_article(self): # -> None:
        ...
    
    def attach_submit_events(self, submit_btn: Button | None, stop_btn: Button | None): # -> None:
        ...
    
    def attach_clear_events(self, clear_btn: ClearButton, input_component_column: Column | None, interpret_component_column: Column | None): # -> None:
        ...
    
    def attach_interpretation_events(self, interpretation_btn: Button | None, interpretation_set: list[Interpretation] | None, input_component_column: Column | None, interpret_component_column: Column | None): # -> None:
        ...
    
    def attach_flagging_events(self, flag_btns: list[Button] | None, clear_btn: ClearButton): # -> None:
        ...
    
    def render_examples(self): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    async def interpret_func(self, *args): # -> list[Any]:
        ...
    
    async def interpret(self, raw_input: list[Any]) -> list[Any]:
        ...
    
    def test_launch(self) -> None:
        """
        Deprecated.
        """
        ...
    


@document()
class TabbedInterface(Blocks):
    """
    A TabbedInterface is created by providing a list of Interfaces, each of which gets
    rendered in a separate tab.
    Demos: stt_or_tts
    """
    def __init__(self, interface_list: list[Interface], tab_names: list[str] | None = ..., title: str | None = ..., theme: Theme | None = ..., analytics_enabled: bool | None = ..., css: str | None = ...) -> None:
        """
        Parameters:
            interface_list: a list of interfaces to be rendered in tabs.
            tab_names: a list of tab names. If None, the tab names will be "Tab 1", "Tab 2", etc.
            title: a title for the interface; if provided, appears above the input and output components in large font. Also used as the tab title when opened in a browser window.
            analytics_enabled: whether to allow basic telemetry. If None, will use GRADIO_ANALYTICS_ENABLED environment variable or default to True.
            css: custom css or path to custom css file to apply to entire Blocks
        Returns:
            a Gradio Tabbed Interface for the given interfaces
        """
        ...
    


def close_all(verbose: bool = ...) -> None:
    ...

