"""
This type stub file was generated by pyright.
"""

from typing import Literal, TYPE_CHECKING
from gradio_client.documentation import document
from gradio.blocks import Block, BlockContext
from gradio.events import Changeable, Selectable

if TYPE_CHECKING:
    ...
@document()
class Row(BlockContext):
    """
    Row is a layout element within Blocks that renders all children horizontally.
    Example:
        with gr.Blocks() as demo:
            with gr.Row():
                gr.Image("lion.jpg", scale=2)
                gr.Image("tiger.jpg", scale=1)
        demo.launch()
    Guides: controlling-layout
    """
    def __init__(self, *, variant: Literal["default", "panel", "compact"] = ..., visible: bool = ..., elem_id: str | None = ..., equal_height: bool = ..., **kwargs) -> None:
        """
        Parameters:
            variant: row type, 'default' (no background), 'panel' (gray background color and rounded corners), or 'compact' (rounded corners and no internal gap).
            visible: If False, row will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
            equal_height: If True, makes every child element have equal height
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(visible: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def style(self, *, equal_height: bool | None = ..., **kwargs): # -> Self:
        """
        Styles the Row.
        Parameters:
            equal_height: If True, makes every child element have equal height
        """
        ...
    


@document()
class Column(BlockContext):
    """
    Column is a layout element within Blocks that renders all children vertically. The widths of columns can be set through the `scale` and `min_width` parameters.
    If a certain scale results in a column narrower than min_width, the min_width parameter will win.
    Example:
        with gr.Blocks() as demo:
            with gr.Row():
                with gr.Column(scale=1):
                    text1 = gr.Textbox()
                    text2 = gr.Textbox()
                with gr.Column(scale=4):
                    btn1 = gr.Button("Button 1")
                    btn2 = gr.Button("Button 2")
    Guides: controlling-layout
    """
    def __init__(self, *, scale: int = ..., min_width: int = ..., variant: Literal["default", "panel", "compact"] = ..., visible: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            scale: relative width compared to adjacent Columns. For example, if Column A has scale=2, and Column B has scale=1, A will be twice as wide as B.
            min_width: minimum pixel width of Column, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in a column narrower than min_width, the min_width parameter will be respected first.
            variant: column type, 'default' (no background), 'panel' (gray background color and rounded corners), or 'compact' (rounded corners and no internal gap).
            visible: If False, column will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(variant: str | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    


class Tabs(BlockContext, Changeable, Selectable):
    """
    Tabs is a layout element within Blocks that can contain multiple "Tab" Components.
    """
    def __init__(self, *, selected: int | str | None = ..., visible: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            selected: The currently selected tab. Must correspond to an id passed to the one of the child TabItems. Defaults to the first TabItem.
            visible: If False, Tabs will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(selected: int | str | None = ...): # -> dict[str, Any]:
        ...
    


@document()
class Tab(BlockContext, Selectable):
    """
    Tab (or its alias TabItem) is a layout element. Components defined within the Tab will be visible when this tab is selected tab.
    Example:
        with gr.Blocks() as demo:
            with gr.Tab("Lion"):
                gr.Image("lion.jpg")
                gr.Button("New Lion")
            with gr.Tab("Tiger"):
                gr.Image("tiger.jpg")
                gr.Button("New Tiger")
    Guides: controlling-layout
    """
    def __init__(self, label: str, *, id: int | str | None = ..., elem_id: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            label: The visual label for the tab
            id: An optional identifier for the tab, required if you wish to control the selected tab from a predict function.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    def get_expected_parent(self) -> type[Tabs]:
        ...
    
    def get_block_name(self): # -> Literal['tabitem']:
        ...
    


TabItem = Tab
@document()
class Group(BlockContext):
    """
    Group is a layout element within Blocks which groups together children so that
    they do not have any padding or margin between them.
    Example:
        with gr.Group():
            gr.Textbox(label="First")
            gr.Textbox(label="Last")
    """
    def __init__(self, *, visible: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            visible: If False, group will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(visible: bool | None = ...): # -> dict[str, Any]:
        ...
    


class Box(BlockContext):
    """
    DEPRECATED.
    Box is a a layout element which places children in a box with rounded corners and
    some padding around them.
    Example:
        with gr.Box():
            gr.Textbox(label="First")
            gr.Textbox(label="Last")
    """
    def __init__(self, *, visible: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            visible: If False, box will be hidden.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(visible: bool | None = ...): # -> dict[str, Any]:
        ...
    
    def style(self, **kwargs): # -> Self:
        ...
    


class Form(BlockContext):
    def __init__(self, *, scale: int = ..., min_width: int = ..., **kwargs) -> None:
        """
        Parameters:
            scale: relative width compared to adjacent Columns. For example, if Column A has scale=2, and Column B has scale=1, A will be twice as wide as B.
            min_width: minimum pixel width of Column, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in a column narrower than min_width, the min_width parameter will be respected first.
        """
        ...
    
    def add_child(self, child: Block): # -> None:
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    


@document()
class Accordion(BlockContext):
    """
    Accordion is a layout element which can be toggled to show/hide the contained content.
    Example:
        with gr.Accordion("See Details"):
            gr.Markdown("lorem ipsum")
    """
    def __init__(self, label, *, open: bool = ..., visible: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        """
        Parameters:
            label: name of accordion section.
            open: if True, accordion is open by default.
            elem_id: An optional string that is assigned as the id of this component in the HTML DOM. Can be used for targeting CSS styles.
        """
        ...
    
    def get_config(self): # -> dict[str, Any]:
        ...
    
    @staticmethod
    def update(open: bool | None = ..., label: str | None = ..., visible: bool | None = ...): # -> dict[str, Any]:
        ...
    


