"""
This type stub file was generated by pyright.
"""

import uvicorn
from typing import TYPE_CHECKING
from gradio.routes import App
from gradio.blocks import Blocks

"""
Defines helper methods useful for setting up ports, launching servers, and
creating tunnels.
"""
if TYPE_CHECKING:
    ...
INITIAL_PORT_VALUE = ...
TRY_NUM_PORTS = ...
LOCALHOST_NAME = ...
GRADIO_API_SERVER = ...
class Server(uvicorn.Server):
    def install_signal_handlers(self): # -> None:
        ...
    
    def run_in_thread(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


def get_first_available_port(initial: int, final: int) -> int:
    """
    Gets the first open port in a specified range of port numbers
    Parameters:
    initial: the initial value in the range of port numbers
    final: final (exclusive) value in the range of port numbers, should be greater than `initial`
    Returns:
    port: the first open port in the range
    """
    ...

def configure_app(app: App, blocks: Blocks) -> App:
    ...

def start_server(blocks: Blocks, server_name: str | None = ..., server_port: int | None = ..., ssl_keyfile: str | None = ..., ssl_certfile: str | None = ..., ssl_keyfile_password: str | None = ..., app_kwargs: dict | None = ...) -> tuple[str, int, str, App, Server]:
    """Launches a local server running the provided Interface
    Parameters:
        blocks: The Blocks object to run on the server
        server_name: to make app accessible on local network, set this to "0.0.0.0". Can be set by environment variable GRADIO_SERVER_NAME.
        server_port: will start gradio app on this port (if available). Can be set by environment variable GRADIO_SERVER_PORT.
        auth: If provided, username and password (or list of username-password tuples) required to access the Blocks. Can also provide function that takes username and password and returns True if valid login.
        ssl_keyfile: If a path to a file is provided, will use this as the private key file to create a local server running on https.
        ssl_certfile: If a path to a file is provided, will use this as the signed certificate for https. Needs to be provided if ssl_keyfile is provided.
        ssl_keyfile_password: If a password is provided, will use this with the ssl certificate for https.
        app_kwargs: Additional keyword arguments to pass to the gradio.routes.App constructor.

    Returns:
        port: the port number the server is running on
        path_to_local_server: the complete address that the local server can be accessed at
        app: the FastAPI app object
        server: the server object that is a subclass of uvicorn.Server (used to close the server)
    """
    ...

def setup_tunnel(local_host: str, local_port: int, share_token: str) -> str:
    ...

def url_ok(url: str) -> bool:
    ...

