"""
This type stub file was generated by pyright.
"""

import typing
import fastapi

OAUTH_CLIENT_ID = ...
OAUTH_CLIENT_SECRET = ...
OAUTH_SCOPES = ...
OPENID_PROVIDER_URL = ...
def attach_oauth(app: fastapi.FastAPI): # -> None:
    ...

class OAuthProfile(typing.Dict):
    """
    A Gradio OAuthProfile object that can be used to inject the profile of a user in a
    function. If a function expects `OAuthProfile` or `Optional[OAuthProfile]` as input,
    the value will be injected from the FastAPI session if the user is logged in. If the
    user is not logged in and the function expects `OAuthProfile`, an error will be
    raised.

    Example:
        import gradio as gr
        from typing import Optional


        def hello(profile: Optional[gr.OAuthProfile]) -> str:
            if profile is None:
                return "I don't know you."
            return f"Hello {profile.name}"


        with gr.Blocks() as demo:
            gr.LoginButton()
            gr.LogoutButton()
            gr.Markdown().attach_load_event(hello, None)
    """
    ...


MOCKED_OAUTH_TOKEN = ...
