"""
This type stub file was generated by pyright.
"""

from typing import Optional
from gradio import components

"""
This module defines various classes that can serve as the `output` to an interface. Each class must inherit from
`OutputComponent`, and each class must define a path to its template. All of the subclasses of `OutputComponent` are
automatically added to a registry, which allows them to be easily referenced in other parts of the code.
"""
def warn_outputs_deprecation(): # -> None:
    ...

class Textbox(components.Textbox):
    def __init__(self, type: str = ..., label: Optional[str] = ...) -> None:
        ...
    


class Image(components.Image):
    """
    Component displays an output image.
    Output type: Union[numpy.array, PIL.Image, str, matplotlib.pyplot, Tuple[Union[numpy.array, PIL.Image, str], List[Tuple[str, float, float, float, float]]]]
    """
    def __init__(self, type: str = ..., plot: bool = ..., label: Optional[str] = ...) -> None:
        """
        Parameters:
        type (str): Type of value to be passed to component. "numpy" expects a numpy array with shape (height, width, 3), "pil" expects a PIL image object, "file" expects a file path to the saved image or a remote URL, "plot" expects a matplotlib.pyplot object, "auto" detects return type.
        plot (bool): DEPRECATED. Whether to expect a plot to be returned by the function.
        label (str): component name in interface.
        """
        ...
    


class Video(components.Video):
    """
    Used for video output.
    Output type: filepath
    """
    def __init__(self, type: Optional[str] = ..., label: Optional[str] = ...) -> None:
        """
        Parameters:
        type (str): Type of video format to be passed to component, such as 'avi' or 'mp4'. Use 'mp4' to ensure browser playability. If set to None, video will keep returned format.
        label (str): component name in interface.
        """
        ...
    


class Audio(components.Audio):
    """
    Creates an audio player that plays the output audio.
    Output type: Union[Tuple[int, numpy.array], str]
    """
    def __init__(self, type: str = ..., label: Optional[str] = ...) -> None:
        """
        Parameters:
        type (str): Type of value to be passed to component. "numpy" returns a 2-set tuple with an integer sample_rate and the data as 16-bit int numpy.array of shape (samples, 2), "file" returns a temporary file path to the saved wav audio file, "auto" detects return type.
        label (str): component name in interface.
        """
        ...
    


class File(components.File):
    """
    Used for file output.
    Output type: Union[file-like, str]
    """
    def __init__(self, label: Optional[str] = ...) -> None:
        """
        Parameters:
        label (str): component name in interface.
        """
        ...
    


class Dataframe(components.Dataframe):
    """
    Component displays 2D output through a spreadsheet interface.
    Output type: Union[pandas.DataFrame, numpy.array, List[Union[str, float]], List[List[Union[str, float]]]]
    """
    def __init__(self, headers: Optional[list[str]] = ..., max_rows: Optional[int] = ..., max_cols: Optional[int] = ..., overflow_row_behaviour: str = ..., type: str = ..., label: Optional[str] = ...) -> None:
        """
        Parameters:
        headers (List[str]): Header names to dataframe. Only applicable if type is "numpy" or "array".
        max_rows (int): Maximum number of rows to display at once. Set to None for infinite.
        max_cols (int): Maximum number of columns to display at once. Set to None for infinite.
        overflow_row_behaviour (str): If set to "paginate", will create pages for overflow rows. If set to "show_ends", will show initial and final rows and truncate middle rows.
        type (str): Type of value to be passed to component. "pandas" for pandas dataframe, "numpy" for numpy array, or "array" for Python array, "auto" detects return type.
        label (str): component name in interface.
        """
        ...
    


class Timeseries(components.Timeseries):
    """
    Component accepts pandas.DataFrame.
    Output type: pandas.DataFrame
    """
    def __init__(self, x: str = ..., y: str | list[str] = ..., label: Optional[str] = ...) -> None:
        """
        Parameters:
        x (str): Column name of x (time) series. None if csv has no headers, in which case first column is x series.
        y (Union[str, List[str]]): Column name of y series, or list of column names if multiple series. None if csv has no headers, in which case every column after first is a y series.
        label (str): component name in interface.
        """
        ...
    


class State(components.State):
    """
    Special hidden component that stores state across runs of the interface.
    Output type: Any
    """
    def __init__(self, label: Optional[str] = ...) -> None:
        """
        Parameters:
        label (str): component name in interface (not used).
        """
        ...
    


class Label(components.Label):
    """
    Component outputs a classification label, along with confidence scores of top categories if provided. Confidence scores are represented as a dictionary mapping labels to scores between 0 and 1.
    Output type: Union[Dict[str, float], str, int, float]
    """
    def __init__(self, num_top_classes: Optional[int] = ..., type: str = ..., label: Optional[str] = ...) -> None:
        """
        Parameters:
        num_top_classes (int): number of most confident classes to show.
        type (str): Type of value to be passed to component. "value" expects a single out label, "confidences" expects a dictionary mapping labels to confidence scores, "auto" detects return type.
        label (str): component name in interface.
        """
        ...
    


class KeyValues:
    """
    Component displays a table representing values for multiple fields.
    Output type: Union[Dict, List[Tuple[str, Union[str, int, float]]]]
    """
    def __init__(self, value: str = ..., *, label: Optional[str] = ..., **kwargs) -> None:
        """
        Parameters:
        value (str): IGNORED
        label (str): component name in interface.
        """
        ...
    


class HighlightedText(components.HighlightedText):
    """
    Component creates text that contains spans that are highlighted by category or numerical value.
    Output is represent as a list of Tuple pairs, where the first element represents the span of text represented by the tuple, and the second element represents the category or value of the text.
    Output type: List[Tuple[str, Union[float, str]]]
    """
    def __init__(self, color_map: dict[str, str] = ..., label: Optional[str] = ..., show_legend: bool = ...) -> None:
        """
        Parameters:
        color_map (Dict[str, str]): Map between category and respective colors
        label (str): component name in interface.
        show_legend (bool): whether to show span categories in a separate legend or inline.
        """
        ...
    


class JSON(components.JSON):
    """
    Used for JSON output. Expects a JSON string or a Python object that is JSON serializable.
    Output type: Union[str, Any]
    """
    def __init__(self, label: Optional[str] = ...) -> None:
        """
        Parameters:
        label (str): component name in interface.
        """
        ...
    


class HTML(components.HTML):
    """
    Used for HTML output. Expects an HTML valid string.
    Output type: str
    """
    def __init__(self, label: Optional[str] = ...) -> None:
        """
        Parameters:
        label (str): component name in interface.
        """
        ...
    


class Carousel(components.Carousel):
    """
    Component displays a set of output components that can be scrolled through.
    """
    def __init__(self, components: components.Component | list[components.Component], label: Optional[str] = ...) -> None:
        """
        Parameters:
        components (Union[List[Component], Component]): Classes of component(s) that will be scrolled through.
        label (str): component name in interface.
        """
        ...
    


class Chatbot(components.Chatbot):
    """
    Component displays a chatbot output showing both user submitted messages and responses
    Output type: List[Tuple[str, str]]
    """
    def __init__(self, label: Optional[str] = ...) -> None:
        """
        Parameters:
        label (str): component name in interface (not used).
        """
        ...
    


class Image3D(components.Model3D):
    """
    Used for 3D image model output.
    Input type: File object of type (.obj, glb, or .gltf)
    """
    def __init__(self, clear_color=..., label: Optional[str] = ...) -> None:
        """
        Parameters:
        label (str): component name in interface.
        optional (bool): If True, the interface can be submitted with no uploaded image, in which case the input value is None.
        """
        ...
    


