"""
This type stub file was generated by pyright.
"""

from PIL import Image
from gradio import wasm_utils

if not wasm_utils.IS_WASM:
    ...
log = ...
def to_binary(x: str | dict) -> bytes:
    """Converts a base64 string or dictionary to a binary string that can be sent in a POST."""
    ...

def extract_base64_data(x: str) -> str:
    """Just extracts the base64 data from a general base64 string."""
    ...

def decode_base64_to_image(encoding: str) -> Image.Image:
    ...

def encode_plot_to_base64(plt): # -> str:
    ...

def get_pil_metadata(pil_image): # -> PngInfo:
    ...

def encode_pil_to_bytes(pil_image, format=...): # -> bytes:
    ...

def encode_pil_to_base64(pil_image): # -> str:
    ...

def encode_array_to_base64(image_array): # -> str:
    ...

def resize_and_crop(img, size, crop_type=...): # -> Image:
    """
    Resize and crop an image to fit the specified size.
    args:
        size: `(width, height)` tuple. Pass `None` for either width or height
        to only crop and resize the other.
        crop_type: can be 'top', 'middle' or 'bottom', depending on this
            value, the image will cropped getting the 'top/left', 'middle' or
            'bottom/right' of the image to fit the size.
    raises:
        ValueError: if an invalid `crop_type` is provided.
    """
    ...

def audio_from_file(filename, crop_min=..., crop_max=...): # -> tuple[Any, ndarray[Any, dtype[Any]]]:
    ...

def audio_to_file(sample_rate, data, filename, format=...): # -> None:
    ...

def convert_to_16_bit_wav(data):
    ...

def ffmpeg_installed() -> bool:
    ...

def video_is_playable(video_filepath: str) -> bool:
    """Determines if a video is playable in the browser.

    A video is playable if it has a playable container and codec.
        .mp4 -> h264
        .webm -> vp9
        .ogg -> theora
    """
    ...

def convert_video_to_playable_mp4(video_path: str) -> str:
    """Convert the video to mp4. If something goes wrong return the original video."""
    ...

