"""
This type stub file was generated by pyright.
"""

"""

Contains the functions that run when `gradio` is called from the command line. Specifically, allows

$ gradio app.py, to run app.py in reload mode where any changes in the app.py file or Gradio library reloads the demo.
$ gradio app.py my_demo.app, to use variable names other than "demo"
"""
def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
