"""
This type stub file was generated by pyright.
"""

import sys
import fastapi
import gradio
from typing import Any, Dict, List, Type
from fastapi import FastAPI
from fastapi.responses import JSONResponse
from gradio_client.documentation import document

"""Implements a FastAPI server to run the gradio interface. Note that some types in this
module use the Optional/Union notation so that they work correctly with pydantic."""
if sys.version_info >= (3, 9):
    ...
else:
    ...
STATIC_TEMPLATE_LIB = ...
STATIC_PATH_LIB = ...
BUILD_PATH_LIB = ...
VERSION = ...
class ORJSONResponse(JSONResponse):
    media_type = ...
    def render(self, content: Any) -> bytes:
        ...
    


def toorjson(value): # -> Markup:
    ...

templates = ...
client = ...
class App(FastAPI):
    """
    FastAPI App Wrapper
    """
    def __init__(self, **kwargs) -> None:
        ...
    
    def configure_app(self, blocks: gradio.Blocks) -> None:
        ...
    
    def get_blocks(self) -> gradio.Blocks:
        ...
    
    def build_proxy_request(self, url_path): # -> Request:
        ...
    
    @staticmethod
    def create_app(blocks: gradio.Blocks, app_kwargs: Dict[str, Any] | None = ...) -> App:
        ...
    


def safe_join(directory: str, path: str) -> str:
    """Safely path to a base directory to avoid escaping the base directory.
    Borrowed from: werkzeug.security.safe_join"""
    ...

def get_types(cls_set: List[Type]): # -> tuple[list[Any], list[Any]]:
    ...

def get_server_url_from_ws_url(ws_url: str): # -> str:
    ...

class Obj:
    """
    Using a class to convert dictionaries into objects. Used by the `Request` class.
    Credit: https://www.geeksforgeeks.org/convert-nested-python-dictionary-to-object/
    """
    def __init__(self, dict_) -> None:
        ...
    
    def __getitem__(self, item): # -> Any:
        ...
    
    def __setitem__(self, item, value): # -> None:
        ...
    
    def __iter__(self): # -> Generator[tuple[str, dict[str, Any]] | tuple[str, Any], Any, None]:
        ...
    
    def __contains__(self, item) -> bool:
        ...
    
    def keys(self): # -> dict_keys[str, Any]:
        ...
    
    def values(self): # -> dict_values[str, Any]:
        ...
    
    def items(self): # -> dict_items[str, Any]:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


@document()
class Request:
    """
    A Gradio request object that can be used to access the request headers, cookies,
    query parameters and other information about the request from within the prediction
    function. The class is a thin wrapper around the fastapi.Request class. Attributes
    of this class include: `headers`, `client`, `query_params`, and `path_params`. If
    auth is enabled, the `username` attribute can be used to get the logged in user.
    Example:
        import gradio as gr
        def echo(name, request: gr.Request):
            print("Request headers dictionary:", request.headers)
            print("IP address:", request.client.host)
            return name
        io = gr.Interface(echo, "textbox", "textbox").launch()
    """
    def __init__(self, request: fastapi.Request | None = ..., username: str | None = ..., **kwargs) -> None:
        """
        Can be instantiated with either a fastapi.Request or by manually passing in
        attributes (needed for websocket-based queueing).
        Parameters:
            request: A fastapi.Request
        """
        ...
    
    def dict_to_obj(self, d): # -> Any:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    


@document()
def mount_gradio_app(app: fastapi.FastAPI, blocks: gradio.Blocks, path: str, gradio_api_url: str | None = ..., app_kwargs: dict[str, Any] | None = ...) -> fastapi.FastAPI:
    """Mount a gradio.Blocks to an existing FastAPI application.

    Parameters:
        app: The parent FastAPI application.
        blocks: The blocks object we want to mount to the parent app.
        path: The path at which the gradio application will be mounted.
        gradio_api_url: The full url at which the gradio app will run. This is only needed if deploying to Huggingface spaces of if the websocket endpoints of your deployed app are on a different network location than the gradio app. If deploying to spaces, set gradio_api_url to 'http://localhost:7860/'
        app_kwargs: Additional keyword arguments to pass to the underlying FastAPI app as a dictionary of parameter keys and argument values. For example, `{"docs_url": "/docs"}`
    Example:
        from fastapi import FastAPI
        import gradio as gr
        app = FastAPI()
        @app.get("/")
        def read_main():
            return {"message": "This is your main app"}
        io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")
        app = gr.mount_gradio_app(app, io, path="/gradio")
        # Then run `uvicorn run:app` from the terminal and navigate to http://localhost:8000/gradio.
    """
    ...

