"""
This type stub file was generated by pyright.
"""

import os
from typing import Dict
from gradio import wasm_utils

MESSAGING_API_ENDPOINT = ...
en = ...
def get_updated_messaging(en: Dict): # -> None:
    ...

if os.getenv("GRADIO_ANALYTICS_ENABLED", "True") == "True" and not wasm_utils.IS_WASM:
    ...
