"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Any, Callable, Literal
from PIL.Image import Image
from gradio import components

class TextArea(components.Textbox):
    """
    Sets: lines=7
    """
    is_template = ...
    def __init__(self, value: str | Callable | None = ..., *, lines: int = ..., max_lines: int = ..., placeholder: str | None = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        ...
    


class Webcam(components.Image):
    """
    Sets: source="webcam", interactive=True
    """
    is_template = ...
    def __init__(self, value: str | Image | np.ndarray | None = ..., *, shape: tuple[int, int] | None = ..., image_mode: Literal["RGB", "L"] = ..., invert_colors: bool = ..., source: Literal["webcam"] = ..., tool: Literal["editor", "select", "sketch", "color-sketch"] | None = ..., type: Literal["numpy", "pil", "filepath"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., mirror_webcam: bool = ..., brush_radius: float | None = ..., brush_color: str = ..., **kwargs) -> None:
        ...
    


class Sketchpad(components.Image):
    """
    Sets: image_mode="L", source="canvas", shape=(28, 28), invert_colors=True, interactive=True
    """
    is_template = ...
    def __init__(self, value: str | Image | np.ndarray | None = ..., *, shape: tuple[int, int] = ..., image_mode: Literal["L"] = ..., invert_colors: bool = ..., source: Literal["canvas"] = ..., tool: Literal["editor", "select", "sketch", "color-sketch"] | None = ..., type: Literal["numpy", "pil", "filepath"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., mirror_webcam: bool = ..., brush_radius: float | None = ..., brush_color: str = ..., **kwargs) -> None:
        ...
    


class Paint(components.Image):
    """
    Sets: source="canvas", tool="color-sketch", interactive=True
    """
    is_template = ...
    def __init__(self, value: str | Image | np.ndarray | None = ..., *, shape: tuple[int, int] | None = ..., image_mode: Literal["RGB"] = ..., invert_colors: bool = ..., source: Literal["canvas"] = ..., tool: Literal["color-sketch"] = ..., type: Literal["numpy", "pil", "filepath"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., mirror_webcam: bool = ..., brush_radius: float | None = ..., brush_color: str = ..., **kwargs) -> None:
        ...
    


class ImageMask(components.Image):
    """
    Sets: source="upload", tool="sketch", interactive=True
    """
    is_template = ...
    def __init__(self, value: str | Image | np.ndarray | None = ..., *, shape: tuple[int, int] | None = ..., image_mode: Literal["RGB", "L"] = ..., invert_colors: bool = ..., source: Literal["upload"] = ..., tool: Literal["sketch"] = ..., type: Literal["numpy", "pil", "filepath"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., mirror_webcam: bool = ..., brush_radius: float | None = ..., brush_color: str = ..., **kwargs) -> None:
        ...
    


class ImagePaint(components.Image):
    """
    Sets: source="upload", tool="color-sketch", interactive=True
    """
    is_template = ...
    def __init__(self, value: str | Image | np.ndarray | None = ..., *, shape: tuple[int, int] | None = ..., image_mode: Literal["RGB", "L"] = ..., invert_colors: bool = ..., source: Literal["upload"] = ..., tool: Literal["color-sketch"] = ..., type: Literal["numpy", "pil", "filepath"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., mirror_webcam: bool = ..., brush_radius: float | None = ..., brush_color: str = ..., **kwargs) -> None:
        ...
    


class Pil(components.Image):
    """
    Sets: type="pil"
    """
    is_template = ...
    def __init__(self, value: str | Image | np.ndarray | None = ..., *, shape: tuple[int, int] | None = ..., image_mode: Literal["RGB", "L"] = ..., invert_colors: bool = ..., source: Literal["upload", "webcam", "canvas"] = ..., tool: Literal["editor", "select", "sketch", "color-sketch"] | None = ..., type: Literal["pil"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., mirror_webcam: bool = ..., brush_radius: float | None = ..., brush_color: str = ..., **kwargs) -> None:
        ...
    


class PlayableVideo(components.Video):
    """
    Sets: format="mp4"
    """
    is_template = ...
    def __init__(self, value: str | Callable | None = ..., *, format: Literal["mp4"] | None = ..., source: Literal["upload", "webcam"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., mirror_webcam: bool = ..., include_audio: bool | None = ..., **kwargs) -> None:
        ...
    


class Microphone(components.Audio):
    """
    Sets: source="microphone"
    """
    is_template = ...
    def __init__(self, value: str | tuple[int, np.ndarray] | Callable | None = ..., *, source: Literal["microphone"] = ..., type: Literal["numpy", "filepath"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., streaming: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        ...
    


class Files(components.File):
    """
    Sets: file_count="multiple"
    """
    is_template = ...
    def __init__(self, value: str | list[str] | Callable | None = ..., *, file_count: Literal["multiple"] = ..., type: Literal["file", "binary"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., **kwargs) -> None:
        ...
    


class Numpy(components.Dataframe):
    """
    Sets: type="numpy"
    """
    is_template = ...
    def __init__(self, value: list[list[Any]] | Callable | None = ..., *, headers: list[str] | None = ..., row_count: int | tuple[int, str] = ..., col_count: int | tuple[int, str] | None = ..., datatype: str | list[str] = ..., type: Literal["numpy"] = ..., max_rows: int | None = ..., max_cols: int | None = ..., overflow_row_behaviour: Literal["paginate", "show_ends"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., wrap: bool = ..., **kwargs) -> None:
        ...
    


class Matrix(components.Dataframe):
    """
    Sets: type="array"
    """
    is_template = ...
    def __init__(self, value: list[list[Any]] | Callable | None = ..., *, headers: list[str] | None = ..., row_count: int | tuple[int, str] = ..., col_count: int | tuple[int, str] | None = ..., datatype: str | list[str] = ..., type: Literal["array"] = ..., max_rows: int | None = ..., max_cols: int | None = ..., overflow_row_behaviour: Literal["paginate", "show_ends"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., wrap: bool = ..., **kwargs) -> None:
        ...
    


class List(components.Dataframe):
    """
    Sets: type="array", col_count=1
    """
    is_template = ...
    def __init__(self, value: list[list[Any]] | Callable | None = ..., *, headers: list[str] | None = ..., row_count: int | tuple[int, str] = ..., col_count: Literal[1] = ..., datatype: str | list[str] = ..., type: Literal["array"] = ..., max_rows: int | None = ..., max_cols: int | None = ..., overflow_row_behaviour: Literal["paginate", "show_ends"] = ..., label: str | None = ..., show_label: bool = ..., interactive: bool | None = ..., visible: bool = ..., elem_id: str | None = ..., wrap: bool = ..., **kwargs) -> None:
        ...
    


Mic = Microphone
