"""
This type stub file was generated by pyright.
"""

import httpx
import gradio
from contextlib import contextmanager
from enum import Enum
from numbers import Number
from pathlib import Path
from typing import Any, Callable, Generator, TYPE_CHECKING, TypeVar, Union
from pydantic import BaseModel
from typing_extensions import ParamSpec
from gradio.blocks import Block, BlockContext, Blocks
from gradio.components import Component

""" Handy utility functions. """
if TYPE_CHECKING:
    ...
JSON_PATH = ...
GRADIO_VERSION = ...
P = ParamSpec("P")
T = TypeVar("T")
def colab_check() -> bool:
    """
    Check if interface is launching from Google Colab
    :return is_colab (bool): True or False
    """
    ...

def kaggle_check() -> bool:
    ...

def sagemaker_check() -> bool:
    ...

def ipython_check() -> bool:
    """
    Check if interface is launching from iPython (not colab)
    :return is_ipython (bool): True or False
    """
    ...

def get_space() -> str | None:
    ...

def is_zero_gpu_space() -> bool:
    ...

def readme_to_html(article: str) -> str:
    ...

def show_tip(interface: gradio.Blocks) -> None:
    ...

def launch_counter() -> None:
    ...

def get_default_args(func: Callable) -> list[Any]:
    ...

def assert_configs_are_equivalent_besides_ids(config1: dict, config2: dict, root_keys: tuple = ...): # -> Literal[True]:
    """Allows you to test if two different Blocks configs produce the same demo.

    Parameters:
    config1 (dict): nested dict with config from the first Blocks instance
    config2 (dict): nested dict with config from the second Blocks instance
    root_keys (Tuple): an interable consisting of which keys to test for equivalence at
        the root level of the config. By default, only "mode" is tested,
        so keys like "version" are ignored.
    """
    ...

def format_ner_list(input_string: str, ner_groups: list[dict[str, str | int]]): # -> list[tuple[str, None]] | list[Any]:
    ...

def delete_none(_dict: dict, skip_value: bool = ...) -> dict:
    """
    Delete keys whose values are None from a dictionary
    """
    ...

def resolve_singleton(_list: list[Any] | Any) -> Any:
    ...

def component_or_layout_class(cls_name: str) -> type[Component] | type[BlockContext]:
    """
    Returns the component, template, or layout class with the given class name, or
    raises a ValueError if not found.

    Parameters:
    cls_name (str): lower-case string class name of a component
    Returns:
    cls: the component class
    """
    ...

def run_coro_in_background(func: Callable, *args, **kwargs): # -> Task[Any]:
    """
    Runs coroutines in background.

    Warning, be careful to not use this function in other than FastAPI scope, because the event_loop has not started yet.
    You can use it in any scope reached by FastAPI app.

    correct scope examples: endpoints in routes, Blocks.process_api
    incorrect scope examples: Blocks.launch

    Use startup_events in routes.py if you need to run a coro in background in Blocks.launch().


    Example:
        utils.run_coro_in_background(fn, *args, **kwargs)

    Args:
        func:
        *args:
        **kwargs:

    Returns:

    """
    ...

def run_sync_iterator_async(iterator):
    """Helper for yielding StopAsyncIteration from sync iterators."""
    ...

class SyncToAsyncIterator:
    """Treat a synchronous iterator as async one."""
    def __init__(self, iterator, limiter) -> None:
        ...
    
    def __aiter__(self): # -> Self:
        ...
    
    async def __anext__(self):
        ...
    


async def async_iteration(iterator):
    ...

class AsyncRequest:
    """
    The AsyncRequest class is a low-level API that allow you to create asynchronous HTTP requests without a context manager.
    Compared to making calls by using httpx directly, AsyncRequest offers several advantages:
        (1) Includes response validation functionality both using validation models and functions.
        (2) Exceptions are handled silently during the request call, which provides the ability to inspect each one
        request call individually in the case where there are multiple asynchronous request calls and some of them fail.
        (3) Provides HTTP request types with AsyncRequest.Method Enum class for ease of usage

    AsyncRequest also offers some util functions such as has_exception, is_valid and status to inspect get detailed
    information about executed request call.

    The basic usage of AsyncRequest is as follows: create a AsyncRequest object with inputs(method, url etc.). Then use it
    with the "await" statement, and then you can use util functions to do some post request checks depending on your use-case.
    Finally, call the get_validated_data function to get the response data.

    You can see example usages in test_utils.py.
    """
    client = ...
    class Method(str, Enum):
        """
        Method is an enumeration class that contains possible types of HTTP request methods.
        """
        ANY = ...
        CONNECT = ...
        HEAD = ...
        GET = ...
        DELETE = ...
        OPTIONS = ...
        PATCH = ...
        POST = ...
        PUT = ...
        TRACE = ...
    
    
    def __init__(self, method: Method, url: str, *, validation_model: type[BaseModel] | None = ..., validation_function: Union[Callable, None] = ..., exception_type: type[Exception] = ..., raise_for_status: bool = ..., client: httpx.AsyncClient | None = ..., **kwargs) -> None:
        """
        Initialize the Request instance.
        Args:
            method(Request.Method) : method of the request
            url(str): url of the request
            *
            validation_model(Type[BaseModel]): a pydantic validation class type to use in validation of the response
            validation_function(Callable): a callable instance to use in validation of the response
            exception_class(Type[Exception]): a exception type to throw with its type
            raise_for_status(bool): a flag that determines to raise httpx.Request.raise_for_status() exceptions.
        """
        ...
    
    def __await__(self) -> Generator[None, Any, AsyncRequest]:
        """
        Wrap Request's __await__ magic function to create request calls which are executed in one line.
        """
        ...
    
    def is_valid(self, raise_exceptions: bool = ...) -> bool:
        """
        Check response object's validity+. Raise exceptions if raise_exceptions flag is True.
        Args:
            raise_exceptions(bool) : a flag to raise exceptions in this check
        Returns:
            bool: validity of the data
        """
        ...
    
    def get_validated_data(self): # -> BaseModel | None:
        ...
    
    @property
    def json(self): # -> Any:
        ...
    
    @property
    def exception(self): # -> Exception | None:
        ...
    
    @property
    def has_exception(self): # -> bool:
        ...
    
    @property
    def raise_exceptions(self): # -> None:
        ...
    
    @property
    def status(self): # -> int | None:
        ...
    


@contextmanager
def set_directory(path: Path | str): # -> Generator[None, Any, None]:
    """Context manager that sets the working directory to the given path."""
    ...

def sanitize_value_for_csv(value: str | Number) -> str | Number:
    """
    Sanitizes a value that is being written to a CSV file to prevent CSV injection attacks.
    Reference: https://owasp.org/www-community/attacks/CSV_Injection
    """
    ...

def sanitize_list_for_csv(values: list[Any]) -> list[Any]:
    """
    Sanitizes a list of values (or a list of list of values) that is being written to a
    CSV file to prevent CSV injection attacks.
    """
    ...

def append_unique_suffix(name: str, list_of_names: list[str]): # -> str:
    """Appends a numerical suffix to `name` so that it does not appear in `list_of_names`."""
    ...

def validate_url(possible_url: str) -> bool:
    ...

def is_update(val): # -> bool:
    ...

def get_continuous_fn(fn: Callable, every: float) -> Callable:
    ...

def function_wrapper(f, before_fn=..., before_args=..., after_fn=..., after_args=...): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], AsyncGenerator[Any, Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], CoroutineType[Any, Any, Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Generator[Any, Any, None]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    ...

def get_function_with_locals(fn: Callable, blocks: Blocks, event_id: str | None): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], AsyncGenerator[Any, Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], CoroutineType[Any, Any, Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Generator[Any, Any, None]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    ...

async def cancel_tasks(task_ids: set[str]): # -> None:
    ...

def set_task_name(task, session_hash: str, fn_index: int, batch: bool): # -> None:
    ...

def get_cancel_function(dependencies: list[dict[str, Any]]) -> tuple[Callable, list[int]]:
    ...

def get_type_hints(fn): # -> dict[Any, Any] | dict[str, Any]:
    ...

def is_special_typed_parameter(name, parameter_types): # -> bool | TypeIs[type[Any]]:
    ...

def check_function_inputs_match(fn: Callable, inputs: list, inputs_as_dict: bool): # -> str | None:
    """
    Checks if the input component set matches the function
    Returns: None if valid, a string error message if mismatch
    """
    ...

def concurrency_count_warning(queue: Callable[P, T]) -> Callable[P, T]:
    ...

class TupleNoPrint(tuple):
    def __repr__(self): # -> Literal['']:
        ...
    
    def __str__(self) -> str:
        ...
    


class MatplotlibBackendMananger:
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


def tex2svg(formula, *args): # -> str:
    ...

def abspath(path: str | Path) -> Path:
    """Returns absolute path of a str or Path path, but does not resolve symlinks."""
    ...

def is_in_or_equal(path_1: str | Path, path_2: str | Path): # -> bool:
    """
    True if path_1 is a descendant (i.e. located within) path_2 or if the paths are the
    same, returns False otherwise.
    Parameters:
        path_1: str or Path (should be a file)
        path_2: str or Path (can be a file or directory)
    """
    ...

def get_serializer_name(block: Block) -> str | None:
    ...

HTML_TAG_RE = ...
def remove_html_tags(raw_html: str | None) -> str:
    ...

def find_user_stack_level() -> int:
    """
    Find the first stack frame not inside Gradio.
    """
    ...

