"""
diff_pipeline/schedulers.py — WebUI scheduler → Diffusers scheduler mapping.

When the Diffusers pipeline (``sd_model.diff_pipeline``) is active, this
module provides a replacement sigma schedule generated by the corresponding
HuggingFace Diffusers scheduler class instead of the custom WebUI sigma
functions.

Only schedulers that already exist in the WebUI are mapped here.  Schedulers
available in Diffusers but absent from the WebUI are intentionally not added.

Supported mappings
------------------
WebUI name          Diffusers class            Extra kwargs
──────────────────  ─────────────────────────  ─────────────────────────────
karras              EulerDiscreteScheduler     use_karras_sigmas=True
exponential         EulerDiscreteScheduler     use_exponential_sigmas=True
sgm_uniform         EulerDiscreteScheduler     timestep_spacing="trailing"
simple              EulerDiscreteScheduler     timestep_spacing="trailing"
beta                EulerDiscreteScheduler     use_beta_sigmas=True
uniform             EulerDiscreteScheduler     timestep_spacing="linspace"
normal              EulerDiscreteScheduler     timestep_spacing="linspace"

Sources
-------
* https://huggingface.co/docs/diffusers/api/schedulers/overview
  (Noise Schedules and Schedule Types table)
* https://huggingface.co/docs/diffusers/api/schedulers/euler
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Optional

import torch  # type: ignore[import-not-found]

from diff_pipeline._cache import lru_cached

if TYPE_CHECKING:
    pass

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Mapping: WebUI scheduler .name → (Diffusers class name, extra kwargs)
# Using string class names so that diffusers is not imported at module load.
#
# Special kwargs recognised by get_diffusers_sigmas() (not forwarded to the
# Diffusers class constructor):
#   _ays_key  — name of an AysSchedules entry; set_timesteps() is called with
#               a fixed timestep list rather than the user-requested step count.
# ---------------------------------------------------------------------------
_SCHEDULER_MAP: dict[str, tuple[str, dict]] = {
    # --- Euler-family (sigma schedule variants) ----------------------------
    # Karras noise schedule — clusters sigmas for better structure detail.
    "karras": ("EulerDiscreteScheduler", {"use_karras_sigmas": True}),
    # Exponential noise schedule.
    "exponential": (
        "EulerDiscreteScheduler",
        {"use_exponential_sigmas": True, "timestep_spacing": "linspace"},
    ),
    # SGM Uniform — samples from the last timestep, evenly divides the rest.
    "sgm_uniform": ("EulerDiscreteScheduler", {"timestep_spacing": "trailing"}),
    # Simple — same trailing strategy as SGM Uniform in Diffusers terms.
    "simple": ("EulerDiscreteScheduler", {"timestep_spacing": "trailing"}),
    # Beta schedule — based on the Beta Sampling paper (arXiv:2407.12173).
    "beta": (
        "EulerDiscreteScheduler",
        {"use_beta_sigmas": True, "timestep_spacing": "linspace"},
    ),
    # Uniform — evenly-spaced timesteps (linspace, Diffusers default).
    "uniform": ("EulerDiscreteScheduler", {"timestep_spacing": "linspace"}),
    # Normal — linear interpolation of log-sigmas; approximated by linspace.
    "normal": ("EulerDiscreteScheduler", {"timestep_spacing": "linspace"}),

    # --- Align Your Steps (fixed SDXL timestep table) ----------------------
    # Uses the 10-step SDXL table from AysSchedules; step count is overridden.
    "align_your_steps": (
        "EulerDiscreteScheduler",
        {"_ays_key": "StableDiffusionXLTimesteps"},
    ),

    # --- DPM-Solver family -------------------------------------------------
    # DPM-Solver++ multi-step — production quality, VP-compatible.
    # Matches WebUI's "DPM++ 2M" sampler family with a Diffusers native schedule.
    "dpm++_2m": ("DPMSolverMultistepScheduler", {"algorithm_type": "dpmsolver++"}),
    # DPM-Solver++ multi-step with Karras sigmas.
    "dpm++_2m_karras": (
        "DPMSolverMultistepScheduler",
        {"algorithm_type": "dpmsolver++", "use_karras_sigmas": True},
    ),
    # DPM-Solver++ single-step — fast, fewer NFE than multi-step.
    "dpm++_singlestep": ("DPMSolverSinglestepScheduler", {"algorithm_type": "dpmsolver++"}),

    # --- UniPC (Unified Predictor-Corrector) --------------------------------
    # High quality at 10–20 steps, VP-compatible, no special sampler required.
    "unipc": ("UniPCMultistepScheduler", {}),

    # --- LMS (Linear Multi-Step, legacy k-diffusion) -----------------------
    "lms": ("LMSDiscreteScheduler", {}),
}

# SDXL default noise schedule parameters used to initialise Diffusers schedulers.
# These match stabilityai/stable-diffusion-xl-base-1.0 scheduler/config.json.
_SDXL_SCHEDULER_CONFIG: dict = {
    "beta_start": 0.00085,
    "beta_end": 0.012,
    "beta_schedule": "scaled_linear",
    "num_train_timesteps": 1000,
}


@lru_cached
def get_diffusers_sigmas(
    scheduler_name: str,
    n: int,
    device: "torch.device",
) -> "Optional[torch.Tensor]":
    """Return a sigma tensor produced by the Diffusers scheduler that
    corresponds to *scheduler_name*, or ``None`` if no mapping exists.

    The returned tensor has shape ``(n + 1,)`` where the final element is
    ``0.0`` — identical to the convention used by the WebUI scheduler
    functions so it can be used as a drop-in replacement.

    Parameters
    ----------
    scheduler_name:
        The canonical WebUI scheduler name (``Scheduler.name``), e.g.
        ``"karras"``, ``"exponential"``.  Case-sensitive; must match the
        ``name`` field in ``modules/sd_schedulers.py``.
    n:
        Number of denoising steps requested.  The scheduler produces
        ``n + 1`` entries (n active sigmas + terminal 0).
    device:
        Target torch device for the returned tensor.

    Returns
    -------
    ``torch.Tensor`` of dtype ``float32`` and shape ``(n + 1,)`` on
    *device* if a mapping is found, otherwise ``None``.
    """
    entry = _SCHEDULER_MAP.get(scheduler_name)
    if entry is None:
        return None

    cls_name, extra_kwargs = entry

    # Lazy import so the module can be imported without diffusers installed.
    try:
        import diffusers.schedulers as _ds  # type: ignore[import-not-found]
        scheduler_cls = getattr(_ds, cls_name)
    except Exception as exc:
        log.warning(
            "DiffPipeline scheduler mapping: cannot import diffusers.schedulers.%s — %s",
            cls_name,
            exc,
        )
        return None

    try:
        kwargs = dict(_SDXL_SCHEDULER_CONFIG)
        kwargs.update(extra_kwargs)

        # _ays_key is a private marker — not a constructor kwarg.
        ays_key: Optional[str] = kwargs.pop("_ays_key", None)

        hf_scheduler = scheduler_cls(**kwargs)

        if ays_key is not None:
            # Fixed timestep table (e.g. Align Your Steps): ignore n and use
            # the predefined SDXL table from AysSchedules.
            try:
                from diffusers.schedulers.scheduling_utils import AysSchedules  # type: ignore[import-not-found]
                ays_timesteps = AysSchedules[ays_key]
            except (ImportError, KeyError) as exc:
                log.warning(
                    "DiffPipeline scheduler mapping: AysSchedules[%r] unavailable (%s) — "
                    "falling back to WebUI scheduler for '%s'",
                    ays_key, exc, scheduler_name,
                )
                return None
            hf_scheduler.set_timesteps(timesteps=ays_timesteps, device=device)
        else:
            hf_scheduler.set_timesteps(n, device=device)

        if not hasattr(hf_scheduler, "sigmas"):
            log.warning(
                "DiffPipeline scheduler mapping: %s has no .sigmas after "
                "set_timesteps — falling back to WebUI scheduler for '%s'",
                cls_name,
                scheduler_name,
            )
            return None

        sigmas = hf_scheduler.sigmas.to(device=device, dtype=torch.float32)

        # Some Diffusers schedulers append an extra trailing zero already;
        # others do not.  Ensure exactly one terminal zero to match WebUI
        # convention of shape (n + 1,).
        if sigmas[-1].item() != 0.0:
            sigmas = torch.cat([sigmas, sigmas.new_zeros(1)])

        # Trim to n+1 if the scheduler emitted more entries.
        if sigmas.shape[0] > n + 1:
            sigmas = sigmas[: n + 1]

        log.debug(
            "DiffPipeline scheduler mapping: using Diffusers %s for '%s' — "
            "sigmas shape=%s  range=[%.4f, %.4f]",
            cls_name,
            scheduler_name,
            tuple(sigmas.shape),
            float(sigmas[-2]),
            float(sigmas[0]),
        )
        return sigmas

    except Exception as exc:
        log.warning(
            "DiffPipeline scheduler mapping: %s raised %s for '%s' — "
            "falling back to WebUI scheduler",
            cls_name,
            exc,
            scheduler_name,
        )
        return None


def is_mapped(scheduler_name: str) -> bool:
    """Return True if *scheduler_name* has a Diffusers equivalent."""
    return scheduler_name in _SCHEDULER_MAP
